/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/accordion/accordion.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Accordion } = scope;
  return (
<Accordion
  items={[
    { key: "a", title: "Section A", content: "..." },
    { key: "b", title: "Section B", content: "..." }
  ]}
  multiple
  defaultValue={["a", "b"]}
/>
  );
}
