/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/accordion/accordion.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Accordion } = scope;
  return (
<Accordion
  card
  items={[
    { key: "ship", title: "Shipping", content: "Free 2-day shipping on orders over $50." },
    { key: "return", title: "Returns", content: "30-day returns, no questions asked." },
    { key: "warranty", title: "Warranty", content: "Two years, parts and labor." }
  ]}
  defaultValue="ship"
/>
  );
}
