/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/accordion/accordion.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Accordion } = scope;
  return (
<Accordion
  items={[
    { key: "billing", title: "Billing", description: "Plan, payment method, invoices.", content: "Manage your plan, payment method, and invoices." },
    { key: "team", title: "Team", description: "Members and roles.", content: "Invite teammates and set their roles." },
    { key: "security", title: "Security", description: "2FA and sessions.", content: "Two-factor authentication and active sessions." }
  ]}
  defaultValue="billing"
/>
  );
}
