/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/pressable/pressable.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, alpha, Text, Pressable } = scope;
  return (
<Pressable
  onPress={() => {}}
  style={({ pressed }) => ({
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignSelf: "flex-start",
    backgroundColor: pressed ? alpha(tokens.primary, 0.8) : tokens.primary,
  })}
>
  <Text style={{ color: "#ffffff", fontWeight: "600" }}>Press me</Text>
</Pressable>
  );
}
