/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/spinner/spinner.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Spinner, Typography, Column } = scope;
  return (
<Card style={{ height: 160 }}>
  <Column fill center alignCenter cozy>
    <Spinner large />
    <Typography small muted>Loading dashboard…</Typography>
  </Column>
</Card>
  );
}
