/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/spinner/spinner.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Spinner } = scope;
  return (
<Card padded>
  <Spinner stacked>Loading…</Spinner>
</Card>
  );
}
