/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/spinner/spinner.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Spinner, Typography, Column } = scope;
  return (
<Card padded>
  <Column alignCenter snug>
    <Spinner />
    <Typography small muted>Loading…</Typography>
  </Column>
</Card>
  );
}
