/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/input-otp/input-otp.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { InputOTP, Column } = scope;
  return (
<Column relaxed>
  <InputOTP small value="123" onChange={() => {}} />
  <InputOTP value="123" onChange={() => {}} />
  <InputOTP large value="123" onChange={() => {}} />
</Column>
  );
}
