/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/input-otp/input-otp.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, InputOTP } = scope;
  return (
<View style={{ flexDirection: "column", gap: 16 }}>
  <InputOTP length={6} value="1234" onChange={() => {}} />
  <InputOTP length={4} value="12" onChange={() => {}} />
</View>
  );
}
