/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/input-otp/input-otp.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { InputOTP, Column } = scope;
  return (
<Column relaxed>
  <InputOTP length={6} groups={3} defaultValue="123" />
  <InputOTP length={6} groups={2} small defaultValue="1234" />
</Column>
  );
}
