/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/input-otp/input-otp.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, InputOTP, Typography, Column } = scope;
  return (
<Stateful initial="">
  {(code, setCode) => (
    <Column snug>
      <InputOTP length={4} onComplete={setCode} />
      <Typography muted>{code === "" ? "Waiting for the 4-digit code" : `Code ${code} received`}</Typography>
    </Column>
  )}
</Stateful>
  );
}
