/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/sparkline/sparkline.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Column, Sparkline } = scope;
  return (
<Column relaxed style={{ maxWidth: 200 }}>
  <Sparkline primary values={[6, 10, 8, 14, 12, 18, 22]} />
  <Sparkline success values={[6, 10, 8, 14, 12, 18, 22]} />
  <Sparkline destructive values={[22, 18, 20, 12, 14, 8, 6]} />
  <Sparkline muted values={[10, 12, 9, 13, 11, 14, 12]} />
</Column>
  );
}
