/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/sparkline/sparkline.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Column, Sparkline } = scope;
  return (
<Column relaxed style={{ maxWidth: 200 }}>
  <Sparkline compact values={[6, 10, 8, 14, 12, 18, 22]} />
  <Sparkline values={[6, 10, 8, 14, 12, 18, 22]} />
  <Sparkline tall values={[6, 10, 8, 14, 12, 18, 22]} />
</Column>
  );
}
