/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/sparkline/sparkline.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Sparkline } = scope;
  return (
<Sparkline values={[4, 8, 6, 12, 10, 16, 14, 18, 16, 20, 24]} style={{ width: 160 }} />
  );
}
