/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/sparkline/sparkline.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Column, Sparkline } = scope;
  return (
<Column relaxed style={{ maxWidth: 200 }}>
  <Sparkline line success values={[187.2, 188.4, 186.9, 189.3, 190.8, 190.1, 191.6]} />
  <Sparkline line destructive values={[191.6, 190.1, 190.8, 188.3, 188.9, 187.4, 186.2]} />
</Column>
  );
}
