/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/popover/popover.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Input, Popover } = scope;
  return (
<Popover inline title="Rename this project?" actionLabel="Rename">
  <Input defaultValue="Identity Platform" />
</Popover>
  );
}
