/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/popover/popover.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Popover } = scope;
  return (
<Popover inline description="Saved to drafts. Publish when ready." actionLabel="Publish" />
  );
}
