/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/popover/popover.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Popover } = scope;
  return (
<Popover
  trigger="Open popover"
  title="Popover"
  description="A short prompt with supporting text and one follow-up action."
  actionLabel="Close"
/>
  );
}
