/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/breadcrumb/breadcrumb.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Breadcrumb, Button } = scope;
  return (
<View style={{ flexDirection: "row", flexWrap: "wrap", alignItems: "flex-start", justifyContent: "space-between", gap: 16 }}>
  <View>
    <View style={{ marginBottom: 8 }}>
      <Breadcrumb items={["Users", "Rachel Chen"]} />
    </View>
    <Text style={{ fontSize: 24, lineHeight: 32, fontWeight: "600", letterSpacing: -0.4, color: tokens.foreground }}>Rachel Chen</Text>
  </View>
  <View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}>
    <Button outline small>Edit</Button>
    <Button primary small>Save</Button>
  </View>
</View>
  );
}
