/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/divider/divider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Button, Divider } = scope;
  return (
<View style={{ width: 320 }}>
  <Divider>
    <Button ghost small>Show more</Button>
  </Divider>
</View>
  );
}
