/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/divider/divider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Divider, Typography, Column } = scope;
  return (
<Column tight style={{ maxWidth: 280 }}>
  <Typography small>Profile</Typography>
  <Typography small>Account</Typography>
  <Typography small>Notifications</Typography>
  <Divider />
  <Typography small>Sign out</Typography>
</Column>
  );
}
