/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/divider/divider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Divider, Typography, Row } = scope;
  return (
<Row alignCenter cozy>
  <Typography small>Edit</Typography>
  <Divider vertical style={{ height: 16 }} />
  <Typography small>Delete</Typography>
</Row>
  );
}
