/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/switch/switch.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Button, Switch } = scope;
  return (
<View style={{ maxWidth: 280, flexDirection: "column", gap: 12 }}>
  <Switch checked>Auto-save drafts</Switch>
  <Button destructive small style={{ alignSelf: "flex-start" }}>Delete account…</Button>
</View>
  );
}
