/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/code-block/code-block.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { CodeBlock, Column } = scope;
  return (
<Column snug>
  <CodeBlock terminal code="npm install @nannier-com/canvas" />
  <CodeBlock terminal code="yarn add @nannier-com/canvas" />
  <CodeBlock terminal code="bun add @nannier-com/canvas" />
</Column>
  );
}
