/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/code-block/code-block.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Badge, CodeBlock } = scope;
  return (
<CodeBlock
  language="tsx"
  code={`export function Hello({ name }: { name: string }) {
  // Greet the current user
  return <Badge primary>Hi {name}</Badge>;
}`}
/>
  );
}
