/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/dialog/dialog.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Dialog } = scope;
  return (
<Dialog
  trigger="Open dialog"
  title="Refund payment"
  description="The refund will be reflected in the customer's bank account within 2 to 3 business days."
  withBody
  confirmLabel="Confirm"
  cancelLabel="Cancel"
  xs
/>
  );
}
