/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/sidebar/sidebar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Typography, Column } = scope;
  return (
<Column tight style={{ width: 420, maxWidth: "100%" }}>
  <Typography h4>Users</Typography>
  <Typography muted>Manage your team members.</Typography>
</Column>
  );
}
