/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/sidebar/sidebar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Button } = scope;
  return (
<View style={{ height: 56, width: 420, maxWidth: "100%", flexDirection: "row", alignItems: "center", gap: 8, borderRadius: 8, borderWidth: 1, borderColor: tokens.border, backgroundColor: tokens.card, paddingHorizontal: 16 }}>
  <Text style={{ fontSize: 16, lineHeight: 24, fontWeight: "600", color: tokens.foreground }}>Dashboard</Text>
  <Button primary small>Search</Button>
  <Button primary small>Filter</Button>
  <Button primary small>Export</Button>
  <Button primary small>New</Button>
</View>
  );
}
