/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/sidebar/sidebar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Command } = scope;
  return (
<Command open defaultActive={0} placeholder="Type a command or search..." groups={[
    { heading: "Actions", items: [
      { label: "Create identity", shortcut: "C" },
      { label: "Invite teammate" }
    ] }
  ]} />
  );
}
