/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/sidebar/sidebar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Card, Typography, Row } = scope;
  return (
<Card style={{ width: 420, maxWidth: "100%" }}>
  <Row between alignCenter style={{ height: 56, paddingHorizontal: 16 }}>
    <Typography lead semibold>Dashboard</Typography>
    <Row snug>
      <Button ghost small>Search</Button>
      <Button primary small>New</Button>
    </Row>
  </Row>
</Card>
  );
}
