/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/sidebar/sidebar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Sidebar, Row } = scope;
  return (
<Row loose alignStart>
  <Sidebar
    bordered
    defaultActive="Dashboard"
    sections={[
      { title: "Main", items: [
        { label: "Dashboard", icon: "layoutGrid" },
        { label: "Inbox", icon: "inbox", badge: "3" },
        { label: "Settings", icon: "settings" }
      ] }
    ]}
  />
  <Sidebar
    bordered
    collapsed
    defaultActive="Dashboard"
    sections={[
      { title: "Main", items: [
        { label: "Dashboard", icon: "layoutGrid" },
        { label: "Inbox", icon: "inbox", badge: "3" },
        { label: "Settings", icon: "settings" }
      ] }
    ]}
  />
</Row>
  );
}
