/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/sidebar/sidebar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Sidebar } = scope;
  return (
<Sidebar
  active="Dashboard"
  sections={[
    { title: "Main", items: [
      { label: "Dashboard", icon: "◉" },
      { label: "Users", icon: "○", badge: "12" },
      { label: "Settings", icon: "◇" }
    ] },
    { title: "Reports", items: [
      { label: "Analytics", icon: "△" }
    ] }
  ]}
/>
  );
}
