/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/sidebar/sidebar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Icon, Sidebar, Typography, Row } = scope;
  return (
<Sidebar
  collapsible
  defaultActive="Dashboard"
  style={{ height: 420 }}
  header={(collapsed) =>
    collapsed ? (
      <Icon layoutGrid primary size={20} />
    ) : (
      <Row snug alignCenter>
        <Icon layoutGrid primary size={20} />
        <Typography semibold>Acme</Typography>
      </Row>
    )
  }
  footer={<Button ghost block small iconLeft={<Icon settings size={16} />}>Settings</Button>}
  sections={[
    { items: [
      { label: "Dashboard", icon: "layoutGrid" },
      { label: "Inbox", icon: "inbox", badge: "3" }
    ] },
    { title: "Reports", icon: "barChart2", collapsible: true, items: [
      { label: "Analytics", icon: "barChart2" },
      { label: "Traffic", icon: "activity" }
    ] },
    { title: "Team", icon: "users", collapsible: true, items: [
      { label: "Members", icon: "users" },
      { label: "Roles", icon: "shield" }
    ] }
  ]}
/>
  );
}
