/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/sidebar/sidebar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { AppShell, Button, Icon, Sidebar, Typography, Row } = scope;
  return (
<AppShell>
  {({ open, setOpen, select }) => (
    <Sidebar
      responsive
      collapsible
      defaultActive="Dashboard"
      open={open}
      onOpenChange={setOpen}
      onSelect={select}
      header={(collapsed) =>
        collapsed ? (
          <Icon layoutGrid primary size={22} />
        ) : (
          <Row snug alignCenter>
            <Icon layoutGrid primary size={22} />
            <Typography body semibold>Acme</Typography>
          </Row>
        )
      }
      footer={(collapsed) =>
        collapsed ? (
          <Button ghost icon small accessibilityLabel="Settings" iconLeft={<Icon settings size={16} />} />
        ) : (
          <Button ghost block small iconLeft={<Icon settings size={16} />}>Settings</Button>
        )
      }
      sections={[
        { items: [
          { label: "Dashboard", icon: "layoutGrid" },
          { label: "Inbox", icon: "inbox", badge: "3" }
        ] },
        { title: "Reports", icon: "barChart2", collapsible: true, items: [
          { label: "Analytics", icon: "barChart2" },
          { label: "Traffic", icon: "activity" }
        ] },
        { title: "Team", icon: "users", collapsible: true, items: [
          { label: "Members", icon: "users" },
          { label: "Roles", icon: "shield" }
        ] }
      ]}
    />
  )}
</AppShell>
  );
}
