/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/action-sheet/action-sheet.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { ActionSheet } = scope;
  return (
<ActionSheet
  trigger="Delete file…"
  title="Delete this file?"
  message="This permanently removes the file. This action cannot be undone."
  actions={[{ label: "Delete File", destructive: true, onPress: () => {} }]}
/>
  );
}
