/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/action-sheet/action-sheet.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, ActionSheet, Button, Typography, Column } = scope;
  return (
<Stateful initial={false}>
  {(open, setOpen) => (
    <Stateful initial="">
      {(picked, setPicked) => (
        <Column snug alignStart>
          <Button outline onPress={() => setOpen(true)}>Share…</Button>
          <ActionSheet
            open={open}
            onOpenChange={setOpen}
            title="Share this document"
            actions={[
              { label: "Copy Link", onPress: () => setPicked("Copy Link") },
              { label: "Send by Email", onPress: () => setPicked("Send by Email") },
            ]}
          />
          <Typography muted>{picked === "" ? "Nothing picked yet" : `Picked ${picked}`}</Typography>
        </Column>
      )}
    </Stateful>
  )}
</Stateful>
  );
}
