/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/navbars/navbars.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, Pressable, Card, Icon, Kbd, Typography, Row, Column } = scope;
  return (
<Card flat style={{ width: "100%", overflow: "hidden" }}>
  <Row alignCenter snug style={{ height: 56, paddingHorizontal: 16 }}>
    <Typography small semibold>Canvas</Typography>
    <Column grow style={{ marginHorizontal: 16, maxWidth: 400 }}>
      <Pressable style={({ pressed }) => [{ flexDirection: "row", height: 34, width: "100%", alignItems: "center", gap: 8, borderRadius: 6, borderWidth: 1, borderColor: tokens.border, backgroundColor: tokens.card, paddingHorizontal: 10 }, pressed ? { opacity: 0.9 } : null]}>
        <Icon search muted size={13} />
        <Column grow>
          <Typography small style={{ textAlign: "left" }}>Search…</Typography>
        </Column>
        <Kbd>⌘K</Kbd>
      </Pressable>
    </Column>
  </Row>
</Card>
  );
}
