/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Alert, Icon } = scope;
  return (
<Alert warning icon={<Icon alertTriangle size={16} />} title="Action required" description="Something needs your attention." />
  );
}
