/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Alert, Button, Row } = scope;
  return (
<Alert success icon="✓" title="Saved" description="Your changes have been saved successfully.">
  <Row snug>
    <Button ghost small>Dismiss</Button>
  </Row>
</Alert>
  );
}
