/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Alert, Icon } = scope;
  return (
<Alert info icon={<Icon info size={16} />} title="Trial expires today" description="Upgrade now or you'll lose access to your projects." />
  );
}
