/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Alert, Button } = scope;
  return (
<Alert
  error
  icon="✕"
  title="Something went wrong"
  description="Could not save your changes. Please try again."
  dismissible
>
  <View style={{ marginTop: 12, flexDirection: "row", gap: 8 }}>
    <Button primary small>Retry</Button>
  </View>
</Alert>
  );
}
