/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Alert, Button } = scope;
  return (
<Alert
  info
  icon="ℹ"
  title="Heads up"
  description="Maintenance window scheduled for Sunday 2:00 UTC."
  dismissible
>
  <View style={{ marginTop: 12, flexDirection: "row", gap: 8 }}>
    <Button link small>Learn more</Button>
  </View>
</Alert>
  );
}
