/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Alert, Icon, Column } = scope;
  return (
<Column snug>
  <Alert
    narrow
    info
    icon={<Icon info size={16} />}
    title="Narrow"
    description="Capped at 320px, the measure of a standard form field."
  />
  <Alert
    wide
    success
    icon="✓"
    title="Wide"
    description="Capped at 640px for roomy content regions; a banner without a measure prop caps at 480px."
  />
  <Alert
    block
    warning
    icon={<Icon alertTriangle size={16} />}
    title="Block"
    description="No cap: the announcement bar fills whatever container it sits in."
  />
</Column>
  );
}
