/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Alert, Button } = scope;
  return (
<Alert
  success
  icon="✓"
  title="All set"
  description="Your changes have been saved successfully."
  dismissible
  actions={<Button ghost small>View changes</Button>}
/>
  );
}
