/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Alert, Button, Icon } = scope;
  return (
<Alert
  info
  icon={<Icon info size={16} />}
  title="Heads up"
  description="Maintenance window scheduled for Sunday 2:00 UTC."
  dismissible
  actions={<Button link small>Learn more</Button>}
/>
  );
}
