/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, View, Alert, Button, Typography, Column } = scope;
  return (
<Stateful initial={0}>
  {(views, setViews) => (
    <Column snug>
      <Alert
        success
        icon="✓"
        title="All set"
        description="Your changes have been saved successfully."
        dismissible
        actions={<Button ghost small onPress={() => setViews(views + 1)}>View changes</Button>}
      />
      <Typography muted>{views === 0 ? "Changes not viewed yet" : `Viewed ${views} ${views === 1 ? "time" : "times"}`}</Typography>
    </Column>
  )}
</Stateful>
  );
}
