/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Alert, Button } = scope;
  return (
<Alert
  error
  icon="✕"
  title="Something went wrong"
  description="Could not save your changes. Please try again."
  dismissible
  actions={<Button primary small>Retry</Button>}
/>
  );
}
