/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Alert, Icon, Typography } = scope;
  return (
<Alert icon={<Icon info size={16} />} title="Design token renamed">
  <Typography small muted>
    The field underline now reads from <Typography code>--p-field-underline</Typography> instead
    of a raw hex value; update any local overrides before upgrading.
  </Typography>
</Alert>
  );
}
