/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/stats/stats.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, shadow, View, Stats } = scope;
  return (
<View style={{ borderRadius: 8, borderWidth: 1, borderColor: tokens.border, backgroundColor: tokens.card, ...shadow("sm"), padding: 24 }}>
  <Stats items={[
    { label: "Revenue", value: "$48.2k" },
    { label: "Orders", value: "842" }
  ]} />
</View>
  );
}
