/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/stats/stats.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stats } = scope;
  return (
<Stats items={[
    { label: "Revenue", value: "$48,250.00", delta: "+12.5%" },
    { label: "Orders", value: "842", delta: "+3.2%" },
    { label: "Conversion", value: "3.6%", delta: "+0.4%" }
  ]} />
  );
}
