/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/stats/stats.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stats } = scope;
  return (
<Stats
  framed
  items={[
    { label: "Total identities", value: "1,847", delta: "+4.2% on the previous week", spark: [1790, 1802, 1811, 1824, 1831, 1840, 1847] },
    { label: "Active sessions", value: "489", delta: "31 sign-ins in the last hour", steady: true, spark: [12, 18, 9, 22, 31, 27, 19, 31], sparkLabel: "Sign-ins per hour, last 24 hours" },
    { label: "Verified identities", value: "81.3%", delta: "1,502 of 1,847 verified", steady: true, share: [{ label: "Verified", value: 1502 }, { label: "Unverified", value: 345 }] },
    { label: "Locked accounts", value: "3", delta: "2 in the last 24h", down: true, share: [{ label: "Last 24 hours", value: 2 }, { label: "Earlier", value: 1 }] }
  ]}
/>
  );
}
