/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/stats/stats.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Icon, Stats, Emblem } = scope;
  return (
<Stats
  items={[
    { label: "Active users", value: "71,897", delta: "+12.3%", icon: <Emblem small><Icon users /></Emblem> },
    { label: "Uptime", value: "99.98%", delta: "last 30 days", steady: true, icon: <Emblem small success><Icon check /></Emblem> },
  ]}
/>
  );
}
