/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/fieldset/fieldset.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Fieldset } = scope;
  return (
<Fieldset legend="Shipping details" items={[
    { label: "", placeholder: "Full name" },
    { label: "", placeholder: "Email" }
  ]} />
  );
}
