/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/field/field.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Field } = scope;
  return (
<Field style={{ maxWidth: 400 }} rows={[
    { label: "Status", value: "Active" },
    { label: "Plan", value: "Pro" }
  ]} />
  );
}
