/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/field/field.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Field } = scope;
  return (
<Field style={{ maxWidth: 400 }} rows={[
    { label: "Client ID", value: "clt_8f2a9b4c7e1d" },
    { label: "Fingerprint", value: "sha256:xK9v..." }
  ]} />
  );
}
