/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/field/field.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Field, Switch } = scope;
  return (
<Field label="Notifications" helper="You can change this at any time.">
  <Switch defaultChecked>Release activity</Switch>
</Field>
  );
}
