/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/field/field.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Field } = scope;
  return (
<Field
  alignEnd
  rows={[
    { label: "Subtotal", value: "$1,240.00" },
    { label: "Tax", value: "$99.20" },
    { label: "Total", value: "$1,339.20", mono: true },
    { label: "Status", status: "Paid" }
  ]}
  style={{ maxWidth: 400 }}
/>
  );
}
