/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/field/field.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Field } = scope;
  return (
<Field
  rows={[
    { label: "User ID", value: "usr_abc123", mono: true },
    { label: "Name", value: "Rachel Chen" },
    { label: "Role", value: "Admin" },
    { label: "Status", status: "Active" }
  ]}
  style={{ maxWidth: 400 }}
/>
  );
}
