/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/combobox/combobox.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Select } = scope;
  return (
<Select label="Size" options={["Small", "Medium", "Large"]} open placeholder="Select a size" style={{ maxWidth: 280 }} />
  );
}
