/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/combobox/combobox.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Combobox } = scope;
  return (
<Combobox label="Size" options={["Small", "Medium", "Large"]} open placeholder="Search…" style={{ maxWidth: 280 }} />
  );
}
