/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/icon-tile/icon-tile.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Icon } = scope;
  return (
<View style={{ height: 40, width: 40, alignItems: "center", justifyContent: "center", borderRadius: 8, backgroundColor: "rgba(79,70,229,0.1)" }}>
  <Icon shield primary />
</View>
  );
}
