/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/icon-tile/icon-tile.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Icon, Row, IconTile } = scope;
  return (
<Row snug alignCenter>
  <IconTile small primary><Icon bell /></IconTile>
  <IconTile primary><Icon bell /></IconTile>
  <IconTile large primary><Icon bell /></IconTile>
</Row>
  );
}
