/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/icon-tile/icon-tile.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Icon, Row, IconTile } = scope;
  return (
<Row snug alignCenter>
  <IconTile primary><Icon shield /></IconTile>
  <IconTile success><Icon check /></IconTile>
  <IconTile destructive><Icon trash /></IconTile>
  <IconTile muted><Icon bell /></IconTile>
</Row>
  );
}
