/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/slider/slider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Slider, Typography, Row } = scope;
  return (
<Row alignCenter relaxed>
  <Slider narrow defaultValue={48} min={0} max={100} />
  <Typography small muted>48</Typography>
</Row>
  );
}
