/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/slider/slider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Slider, Typography, Column } = scope;
  return (
<Column snug style={{ maxWidth: 320 }}>
  <Typography small medium>Volume</Typography>
  <Slider value={65} min={0} max={100} />
</Column>
  );
}
