/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/slider/slider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Slider, Typography, Row, Column } = scope;
  return (
<Row alignCenter relaxed style={{ maxWidth: 320 }}>
  <Column fill>
    <Slider value={48} min={0} max={100} />
  </Column>
  <Typography small muted style={{ minWidth: 32, textAlign: "right" }}>48</Typography>
</Row>
  );
}
