/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/slider/slider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Slider } = scope;
  return (
<View style={{ maxWidth: 320, flexDirection: "row", alignItems: "center", gap: 16 }}>
  <Slider value={48} min={0} max={100} style={{ flex: 1 }} />
  <Text style={{ fontSize: 14, lineHeight: 20, color: tokens["muted-foreground"], minWidth: 32, textAlign: "right" }}>48</Text>
</View>
  );
}
