/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Form } = scope;
  return (
<Form twoColumn submitLabel="Save" style={{ maxWidth: 560 }} fields={[
    { label: "Street address", placeholder: "123 Market St" },
    { label: "ZIP", placeholder: "94103" }
  ]} />
  );
}
