/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Form } = scope;
  return (
<Form twoColumn submitLabel="Sign in" style={{ width: 360, maxWidth: "100%" }} fields={[
    { label: "Email", placeholder: "you@example.com" },
    { label: "Password" }
  ]} />
  );
}
