/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Form } = scope;
  return (
<Form
  twoColumn
  fields={[
    { label: "First name", placeholder: "Ada" },
    { label: "Last name", placeholder: "King" },
    { label: "Email", placeholder: "ada@example.com" }
  ]}
  submitLabel="Create"
  cancelLabel="Cancel"
  style={{ maxWidth: 560 }}
/>
  );
}
