/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Form } = scope;
  return (
<Form
  sidebar
  sections={[
    { title: "Personal info", description: "This information will be displayed on your public profile.", fields: [
      { label: "Full name", value: "Rachel Chen" },
      { label: "Email", value: "rachel@example.com" }
    ] },
    { title: "Notifications", description: "Choose how you'd like to be notified.", checkboxes: [
      { label: "Email notifications", checked: true },
      { label: "SMS alerts" }
    ] }
  ]}
  submitLabel="Save"
  style={{ width: 720, maxWidth: "100%" }}
/>
  );
}
