/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Form, Input } = scope;
  return (
<Form submitLabel="Create account" style={{ width: 360, maxWidth: "100%" }}>
  <Input block label="Email" required placeholder="you@example.com" />
  <Input block label="Password" required />
  <Input block label="Referral code" placeholder="Optional" />
</Form>
  );
}
