/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/dropdown/dropdown.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Avatar, Dropdown } = scope;
  return (
<Dropdown
  items={[
    { label: "Profile", icon: "user" },
    { label: "Settings", icon: "settings" },
    { label: "Log out", icon: "logOut", separatorBefore: true }
  ]}
>
  <Avatar name="Rachel Chen" />
</Dropdown>
  );
}
