/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/dropdown/dropdown.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Dropdown } = scope;
  return (
<Dropdown
  trigger="Actions"
  disabled
  items={[
    { label: "Edit profile", icon: "pencil" },
    { label: "Duplicate", icon: "copy" },
    { label: "Settings", icon: "settings" }
  ]}
/>
  );
}
