/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/action-panels/action-panels.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Card, Typography, Row, Column } = scope;
  return (
<Card padded style={{ maxWidth: 460 }}>
  <Row alignStart loose>
    <Column fill tight>
      <Typography lead semibold>Discard unsaved changes?</Typography>
      <Typography small muted>You have unsaved edits in this form. Leaving now will lose all progress.</Typography>
    </Column>
    <Row snug>
      <Button outline small>Cancel</Button>
      <Button destructive small>Discard</Button>
    </Row>
  </Row>
</Card>
  );
}
