/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/action-panels/action-panels.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, ActionPanel, Typography, Column } = scope;
  return (
<Stateful initial={0}>
  {(deletes, setDeletes) => (
    <Column snug>
      <ActionPanel
        title="Delete this project"
        description="Once you delete a project, there is no going back. Please be certain."
        actionLabel="Delete project"
        destructive
        onAction={() => setDeletes(deletes + 1)}
      />
      <Typography muted>{deletes === 0 ? "Nothing deleted yet" : `Delete fired ${deletes} ${deletes === 1 ? "time" : "times"}`}</Typography>
    </Column>
  )}
</Stateful>
  );
}
