/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/action-panels/action-panels.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, ActionPanel, AlertDialog, Column } = scope;
  return (
<Stateful initial={false}>
  {(open, setOpen) => (
    <Column snug>
      <ActionPanel
        title="Delete this project"
        description="Once you delete a project, there is no going back. Please be certain."
        actionLabel="Delete project"
        destructive
        onAction={() => setOpen(true)}
      />
      <AlertDialog
        open={open}
        onOpenChange={setOpen}
        destructive
        title="Delete this project?"
        description="This permanently removes the project and all of its data. This action cannot be undone."
        confirmLabel="Delete"
      />
    </Column>
  )}
</Stateful>
  );
}
