/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/action-panels/action-panels.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { ActionPanel } = scope;
  return (
<ActionPanel
  title="Discard unsaved changes?"
  description="You have unsaved edits in this form. Leaving now will lose all progress."
  actionLabel="Discard"
  destructive
  inline
/>
  );
}
