/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/card/card.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card } = scope;
  return (
<Card
  onPress={() => {}}
  title="Recent activity"
  body="A labeled content surface. Drop fields, a list, or any module of content here."
/>
  );
}
