/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/card/card.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Card, DescriptionList } = scope;
  return (
<Card title="Identity" description="Core attributes" actions={<Button ghost small>Edit</Button>}>
  <DescriptionList
    items={[
      { term: "ID", value: "6f1c2a", mono: true },
      { term: "State", value: "Active", status: true },
    ]}
  />
</Card>
  );
}
