/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/card/card.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { shadow, Card } = scope;
  return (
<Card
  padded
  onPress={() => {}}
  title="Anything goes here"
  body="The card surface gives you the border, radius, and shadow. You bring the content."
/>
  );
}
