/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/card/card.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Image, Button, Card, Typography, Row, Column } = scope;
  return (
<Card style={{ width: 320, maxWidth: "100%" }}>
  <Column cozy>
    <Image source={{ uri: "/kira-tanaka.jpg" }} width="100%" height={180} radius="md" alt="Portrait of Kira Tanaka" />
    <Column tight>
      <Typography h5 semibold>Kira Tanaka</Typography>
      <Typography small muted>Design engineer. Ships the pixels and the pipeline that delivers them.</Typography>
    </Column>
    <Row snug>
      <Button primary small>Follow</Button>
      <Button outline small>Message</Button>
    </Row>
  </Column>
</Card>
  );
}
