/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/icon/icon.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Icon, Typography, Row } = scope;
  return (
<Row alignCenter snug>
  <Icon info muted size={16} />
  <Typography small muted>Optional, used only for recovery</Typography>
</Row>
  );
}
