/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/icon/icon.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Icon } = scope;
  return (
<View style={{ flexDirection: "row", alignItems: "center", gap: 6 }}>
  <Icon info muted size={16} />
  <Text style={{ fontSize: 14, lineHeight: 20, color: tokens["muted-foreground"] }}>Optional, used only for recovery</Text>
</View>
  );
}
