/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/code-block/code-block.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Text, CodeBlock } = scope;
  return (
<View style={{ maxWidth: 360, gap: 6 }}>
  <Text style={{ fontSize: 14, lineHeight: 28 }}>Run the setup command:</Text>
  <CodeBlock code={`npm install @olympusoss/canvas
npm run build`} />
</View>
  );
}
