/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/board/board.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, applyBoardMove, Board } = scope;
  return (
<Stateful initial={[
  { id: "t1", columnId: "todo", title: "Rotate webhook secrets" },
  { id: "t2", columnId: "todo", title: "Draft the design review" },
]}>
  {(items, setItems) => (
    <Board
      columns={[
        { id: "todo", label: "To do", badge: "WIP 2" },
        { id: "doing", label: "Doing" },
      ]}
      items={items}
      emptyLabel="Drop tasks here"
      onMove={(move) => setItems(applyBoardMove(items, move))}
    />
  )}
</Stateful>
  );
}
