/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/drag-drop/drag-drop.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Draggable, DragDropProvider, DragHandle, DropZone, RowMenu, Typography, Row } = scope;
  return (
<DragDropProvider>
  <DropZone id="list" label="Tasks" style={{ width: 280, maxWidth: "100%", minHeight: 96 }}>
    <Draggable id="a" data={{ id: "a", zone: "list" }} label="Design review">
      <Card compact>
        <Row between alignCenter>
          <Typography small>Design review</Typography>
          <Row snug alignCenter>
            <DragHandle label="Reorder Design review" />
            <RowMenu items={[{ label: "Move to Doing", icon: "arrowRight" }]} triggerLabel="Move Design review" />
          </Row>
        </Row>
      </Card>
    </Draggable>
  </DropZone>
</DragDropProvider>
  );
}
