/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/drag-drop/drag-drop.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, applyDrop, Card, Draggable, DragDropProvider, DragHandle, DropZone, Typography, Row, Column } = scope;
  return (
<Stateful initial={[
  { id: "t1", zone: "todo", title: "Rotate secrets" },
  { id: "t2", zone: "todo", title: "Draft the review" },
  { id: "t3", zone: "doing", title: "SSO rollout" },
]}>
  {(cards, setCards) => (
    <Row relaxed alignStart>
      <DragDropProvider>
        <Row relaxed alignStart>
          {["todo", "doing"].map((zone) => (
            <DropZone key={zone} id={zone} label={zone === "todo" ? "To do" : "Doing"} onDrop={(e) => setCards(applyDrop(cards, e))} style={{ width: 200, maxWidth: "100%", minHeight: 120 }}>
              <Column snug>
                <Typography small semibold>{zone === "todo" ? "To do" : "Doing"}</Typography>
                {cards.filter((c) => c.zone === zone).map((c) => (
                  <Draggable key={c.id} id={c.id} data={c} label={c.title}>
                    <Card compact>
                      <Row between alignCenter>
                        <Typography small>{c.title}</Typography>
                        <DragHandle label={`Reorder ${c.title}`} />
                      </Row>
                    </Card>
                  </Draggable>
                ))}
              </Column>
            </DropZone>
          ))}
        </Row>
      </DragDropProvider>
    </Row>
  )}
</Stateful>
  );
}
