/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/drag-drop/drag-drop.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Draggable, DragDropProvider, DragHandle, DropZone, Typography, Row, Column } = scope;
  return (
<DragDropProvider>
  <DropZone id="list" label="Tasks" style={{ width: 280, maxWidth: "100%", minHeight: 96 }}>
    <Column snug>
      <Draggable id="a" data={{ id: "a", zone: "list" }} label="Design review">
        <Card compact>
          <Row between alignCenter>
            <Typography small>Design review</Typography>
            <DragHandle label="Reorder Design review" />
          </Row>
        </Card>
      </Draggable>
      <Draggable id="b" data={{ id: "b", zone: "list" }} disabled label="Locked task">
        <Card compact>
          <Row between alignCenter>
            <Typography small muted>Locked task</Typography>
            <DragHandle label="Locked task" />
          </Row>
        </Card>
      </Draggable>
    </Column>
  </DropZone>
</DragDropProvider>
  );
}
