/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/dashboard-grid/dashboard-grid.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { DashboardGrid, BarList } = scope;
  return (
<DashboardGrid
  unlocked
  order={["signups", "revenue"]}
  items={[
    { id: "revenue", span: 6, title: "Revenue", content: <BarList title="Revenue" items={[{ label: "Pro", value: 82 }]} /> },
    { id: "signups", span: 6, title: "Signups", content: <BarList title="Signups" items={[{ label: "Web", value: 64 }]} /> },
  ]}
/>
  );
}
