/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/dashboard-grid/dashboard-grid.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, DashboardGrid } = scope;
  return (
<DashboardGrid
  items={[
    {
      id: "signups",
      span: 6,
      title: "Signups",
      content: (
        <View style={{ backgroundColor: tokens.card, borderRadius: 12, padding: 16 }}>
          <Text style={{ fontSize: 24, fontWeight: "600", color: tokens.foreground }}>1,204</Text>
        </View>
      ),
    },
  ]}
/>
  );
}
