/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/dashboard-grid/dashboard-grid.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, CardContent, CardHeader, CardTitle, DashboardGrid, Typography, BarList } = scope;
  return (
<DashboardGrid
  items={[
    {
      id: "signups",
      span: 6,
      title: "Signups",
      content: (
        <Card>
          <CardHeader>
            <CardTitle>Signups</CardTitle>
          </CardHeader>
          <CardContent>
            <Typography h2>1,204</Typography>
          </CardContent>
        </Card>
      ),
    },
    { id: "revenue", span: 6, title: "Revenue", content: <BarList title="Revenue" items={[{ label: "Pro", value: 82 }]} /> },
  ]}
/>
  );
}
