/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/skeleton/skeleton.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View } = scope;
  return (
<View style={{ backgroundColor: tokens.muted, borderRadius: 6, width: 40, height: 40 }} />
  );
}
