/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/skeleton/skeleton.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Skeleton, Column } = scope;
  return (
<Column snug style={{ width: 320 }}>
  <Skeleton text animate />
  <Skeleton text animate style={{ width: "60%" }} />
</Column>
  );
}
