/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/badge/badge.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Badge } = scope;
  return (
<View style={{ flexDirection: "row", flexWrap: "wrap", gap: 4 }}>
  <Badge secondary>authorization_code</Badge>
  <Badge secondary>refresh_token</Badge>
  <Badge secondary>client_credentials</Badge>
</View>
  );
}
