/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/badge/badge.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Badge, Card, BadgeGroup } = scope;
  return (
<Card padded>
  <BadgeGroup>
    <Badge outline>draft</Badge>
    <Badge outline>internal</Badge>
  </BadgeGroup>
</Card>
  );
}
