/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/badge/badge.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Badge, BadgeGroup } = scope;
  return (
<BadgeGroup tight>
  <Badge secondary mono>authorization_code</Badge>
  <Badge secondary mono>refresh_token</Badge>
  <Badge secondary mono>client_credentials</Badge>
</BadgeGroup>
  );
}
