/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/badge/badge.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Badge, Typography, Row, BadgeGroup } = scope;
  return (
<Row wrap alignCenter snug>
  <Typography lead semibold>Rachel Chen</Typography>
  <BadgeGroup>
    <Badge status success>active</Badge>
    <Badge secondary>employee</Badge>
  </BadgeGroup>
</Row>
  );
}
