/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/stepper/stepper.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stepper, Typography, Column } = scope;
  return (
<Column snug>
  <Typography small medium>Quantity</Typography>
  <Stepper defaultValue={1} min={1} max={9} onChange={() => {}} />
</Column>
  );
}
