/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/stepper/stepper.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stepper, Row } = scope;
  return (
<Row alignCenter relaxed>
  <Stepper small defaultValue={2} min={0} max={10} onChange={() => {}} />
  <Stepper defaultValue={2} min={0} max={10} onChange={() => {}} />
  <Stepper large defaultValue={2} min={0} max={10} onChange={() => {}} />
</Row>
  );
}
