/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/stepper/stepper.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stepper } = scope;
  return (
<Stepper label="Quantity" description="Up to 10 per order." defaultValue={1} min={1} max={10} />
  );
}
