/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/image/image.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, Image } = scope;
  return (
<Image
  source={{ uri: "/liang-bao.jpg" }}
  resizeMode="contain"
  style={{ width: 160, height: 120, borderRadius: 12, backgroundColor: tokens.muted }}
/>
  );
}
