/*
 * Determines WHICH packages the Canvas docs app actually ships, and writes the answer to
 * tools/noticegen/shipped.json for tools/noticegen/generate.ts to turn into licence data.
 *
 * This is a separate, slow step on purpose. It runs a real Metro export, so it takes a
 * minute or two; `notices:gen` and its --check counterpart read the committed JSON and
 * stay fast enough for CI.
 *
 * WHY NOT JUST WALK package.json. The obvious approach, a breadth-first walk of the
 * runtime dependency closure, is wrong here, and quietly so. `expo` declares its own CLI
 * as a regular dependency, so the closure drags in the entire build toolchain: it reports
 * 531 packages including lightningcss (MPL-2.0), node-forge (BSD-3-Clause OR GPL-2.0),
 * argparse, caniuse-lite and mdn-data. None of those reach the app. Publishing that list
 * would attribute copyleft code the app does not contain, which is worse than useless on
 * a page whose whole job is to be accurate.
 *
 * TWO SIGNALS, UNIONED:
 *
 *   1. JAVASCRIPT. Export the web bundle with source maps and read the `sources` array.
 *      Every entry under node_modules names a package that survived tree-shaking and is
 *      really in the bundle. This reproduces the 73-package figure from the original
 *      hand audit in store/SUBMISSION.md.
 *
 *      The map is written to a temp directory and thrown away. It must never land in
 *      docs/dist: the shipped source maps previously exposed 363 of the kit's own source
 *      files on the public site, which is why `build:web` no longer emits them.
 *
 *   2. NATIVE. A package with native code is linked into the .ipa/.aab whether or not its
 *      JavaScript survives, so tree-shaking says nothing about it. Expo autolinks any
 *      dependency carrying an expo-module.config.json, so that file is the signal.
 *
 * Run: bun run notices:scan   (then `bun run notices:gen`, then commit both outputs)
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync, rmSync, mkdtempSync, readdirSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "../..");
const docs = join(repo, "docs");
const OUT = join(here, "shipped.json");

// ---- signal 1: what is really in the JavaScript bundle -------------------------------

const outDir = mkdtempSync(join(tmpdir(), "canvas-noticescan-"));
console.log("notices:scan: exporting the web bundle with source maps (this takes a minute)...");

try {
  execFileSync("npx", ["expo", "export", "-p", "web", "--source-maps", "--output-dir", outDir], {
    cwd: docs,
    stdio: ["ignore", "pipe", "pipe"],
    env: { ...process.env, CI: "1" },
  });
} catch (err) {
  console.error("notices:scan: the export failed, so the shipped set cannot be determined.");
  console.error(String((err as { stderr?: Buffer }).stderr ?? err));
  rmSync(outDir, { recursive: true, force: true });
  process.exit(1);
}

const jsDir = join(outDir, "_expo/static/js/web");
const maps = existsSync(jsDir) ? readdirSync(jsDir).filter((f) => f.endsWith(".js.map")) : [];
if (maps.length === 0) {
  console.error(`notices:scan: no source map found under ${jsDir}; nothing to read.`);
  rmSync(outDir, { recursive: true, force: true });
  process.exit(1);
}

const fromBundle = new Set<string>();
let sourceFiles = 0;
for (const m of maps) {
  const map = JSON.parse(readFileSync(join(jsDir, m), "utf8")) as { sources: string[] };
  sourceFiles += map.sources.length;
  for (const src of map.sources) {
    // Take the LAST match so a nested node_modules attributes to the inner package.
    const hits = [...src.matchAll(/node_modules\/((?:@[^/]+\/)?[^/]+)/g)];
    if (hits.length) fromBundle.add(hits[hits.length - 1][1]);
  }
}
rmSync(outDir, { recursive: true, force: true });

// ---- signal 2: what autolinks native code -------------------------------------------

const fromNative = new Set<string>();
for (const base of [join(docs, "node_modules"), join(repo, "node_modules")]) {
  if (!existsSync(base)) continue;
  for (const entry of readdirSync(base)) {
    const dirs = entry.startsWith("@")
      ? readdirSync(join(base, entry)).map((s) => `${entry}/${s}`)
      : [entry];
    for (const name of dirs) {
      if (existsSync(join(base, name, "expo-module.config.json"))) fromNative.add(name);
    }
  }
}

// ---- union and write -----------------------------------------------------------------

const packages = [...new Set([...fromBundle, ...fromNative])].sort();
const nativeOnly = [...fromNative].filter((n) => !fromBundle.has(n)).sort();

writeFileSync(
  OUT,
  `${JSON.stringify(
    {
      _comment:
        "GENERATED by tools/noticegen/scan.ts (bun run notices:scan). The packages the docs app actually ships: the union of what survives into the JS bundle (read from a source-mapped export) and what autolinks native code (an expo-module.config.json). Re-run after changing the app's dependencies, then run notices:gen.",
      counts: {
        javascriptBundle: fromBundle.size,
        nativeModules: fromNative.size,
        nativeOnly: nativeOnly.length,
        total: packages.length,
      },
      nativeOnly,
      packages,
    },
    null,
    2,
  )}\n`,
);

console.log(`notices:scan: wrote ${OUT}`);
console.log(`  ${sourceFiles} source files in the map`);
console.log(`  ${fromBundle.size} packages in the JS bundle`);
console.log(`  ${fromNative.size} autolinked native modules (${nativeOnly.length} of them native-only)`);
console.log(`  ${packages.length} shipped packages in total`);
