/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/text/text.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, alpha, View, Text } = scope;
  return (
<View style={{ gap: 4 }}>
  <Text style={{ color: tokens.primary, fontWeight: "600" }}>Primary</Text>
  <Text style={{ color: tokens.destructive, fontWeight: "600" }}>Destructive</Text>
  <Text style={{ color: alpha(tokens.foreground, 0.6) }}>Muted</Text>
</View>
  );
}
