/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/geo-map/geo-map.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { GeoMap } = scope;
  return (
<GeoMap
  compact
  title="Edge nodes"
  points={[
    { label: "Ashburn", lat: 39.0438, lng: -77.4874, count: 42 },
    { label: "Frankfurt", lat: 50.1109, lng: 8.6821, count: 36 },
    { label: "Mumbai", lat: 19.076, lng: 72.8777, count: 18 },
    { label: "Sydney", lat: -33.8688, lng: 151.2093, count: 9 },
  ]}
/>
  );
}
