/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/dialog/dialog.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Dialog, Field, Typography, Row, Column } = scope;
  return (
<Dialog open large>
  <Column relaxed>
    <Column tight>
      <Typography lead semibold>Edit profile</Typography>
      <Typography small muted>Update how your name and email appear to teammates.</Typography>
    </Column>
    <Column relaxed>
      <Field block label="Name" value="Ada Lovelace" />
      <Field block label="Email" value="ada@example.com" />
    </Column>
    <Row end snug alignCenter>
      <Button outline small>Cancel</Button>
      <Button primary small>Save changes</Button>
    </Row>
  </Column>
</Dialog>
  );
}
