/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/dialog/dialog.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Dialog, Field, Typography, Row, Column } = scope;
  return (
<Dialog open small>
  <Column relaxed>
    <Typography lead semibold>Rename</Typography>
    <Field label="Name" value="Untitled" />
    <Row end snug alignCenter>
      <Button outline small>Cancel</Button>
      <Button primary small>Save</Button>
    </Row>
  </Column>
</Dialog>
  );
}
