/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/carousel/carousel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Carousel } = scope;
  return (
<Carousel
  items={[
    { key: "do1", content: (
      <View style={{ height: 140, alignItems: "center", justifyContent: "center", backgroundColor: tokens.muted }}>
        <Text style={{ fontSize: 16, fontWeight: "500", color: tokens.foreground }}>Step 1</Text>
      </View>
    ) },
    { key: "do2", content: (
      <View style={{ height: 140, alignItems: "center", justifyContent: "center", backgroundColor: tokens.muted }}>
        <Text style={{ fontSize: 16, fontWeight: "500", color: tokens.foreground }}>Step 2</Text>
      </View>
    ) }
  ]}
  defaultIndex={0}
  onIndexChange={() => {}}
/>
  );
}
