/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/carousel/carousel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Carousel } = scope;
  return (
<Carousel
  items={[
    { key: "one", content: (
      <View style={{ height: 160, alignItems: "center", justifyContent: "center", backgroundColor: tokens.muted }}>
        <Text style={{ fontSize: 18, fontWeight: "600", color: tokens.foreground }}>Slide 1</Text>
      </View>
    ) },
    { key: "two", content: (
      <View style={{ height: 160, alignItems: "center", justifyContent: "center", backgroundColor: tokens.muted }}>
        <Text style={{ fontSize: 18, fontWeight: "600", color: tokens.foreground }}>Slide 2</Text>
      </View>
    ) },
    { key: "three", content: (
      <View style={{ height: 160, alignItems: "center", justifyContent: "center", backgroundColor: tokens.muted }}>
        <Text style={{ fontSize: 18, fontWeight: "600", color: tokens.foreground }}>Slide 3</Text>
      </View>
    ) }
  ]}
  defaultIndex={0}
  onIndexChange={() => {}}
/>
  );
}
