/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/carousel/carousel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Carousel } = scope;
  return (
<Carousel
  defaultIndex={1}
  loop
  items={[
    { key: "x", content: (
      <View style={{ height: 140, alignItems: "center", justifyContent: "center", backgroundColor: tokens.muted }}>
        <Text style={{ fontSize: 16, fontWeight: "500", color: tokens.foreground }}>First</Text>
      </View>
    ) },
    { key: "y", content: (
      <View style={{ height: 140, alignItems: "center", justifyContent: "center", backgroundColor: tokens.muted }}>
        <Text style={{ fontSize: 16, fontWeight: "500", color: tokens.foreground }}>Second</Text>
      </View>
    ) },
    { key: "z", content: (
      <View style={{ height: 140, alignItems: "center", justifyContent: "center", backgroundColor: tokens.muted }}>
        <Text style={{ fontSize: 16, fontWeight: "500", color: tokens.foreground }}>Third</Text>
      </View>
    ) }
  ]}
  onIndexChange={() => {}}
/>
  );
}
