/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/carousel/carousel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Carousel } = scope;
  return (
<Carousel
  showArrows={false}
  items={[
    { key: "a", content: (
      <View style={{ height: 140, alignItems: "center", justifyContent: "center", backgroundColor: tokens.muted }}>
        <Text style={{ fontSize: 16, fontWeight: "500", color: tokens.foreground }}>Featured</Text>
      </View>
    ) },
    { key: "b", content: (
      <View style={{ height: 140, alignItems: "center", justifyContent: "center", backgroundColor: tokens.muted }}>
        <Text style={{ fontSize: 16, fontWeight: "500", color: tokens.foreground }}>Popular</Text>
      </View>
    ) }
  ]}
  defaultIndex={0}
  onIndexChange={() => {}}
/>
  );
}
