/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/carousel/carousel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, Carousel, Typography, Column } = scope;
  return (
<Carousel
  showArrows={false}
  items={[
    { key: "a", content: (
      <Column alignCenter center style={{ height: 140, backgroundColor: tokens.muted }}> {/* docgen-allow-style: demo placeholder slide surface */}
        <Typography lead medium>Featured</Typography>
      </Column>
    ) },
    { key: "b", content: (
      <Column alignCenter center style={{ height: 140, backgroundColor: tokens.muted }}> {/* docgen-allow-style: demo placeholder slide surface */}
        <Typography lead medium>Popular</Typography>
      </Column>
    ) }
  ]}
  defaultIndex={0}
  onIndexChange={() => {}}
/>
  );
}
