/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/empty-state/empty-state.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { EmptyState } = scope;
  return (
<EmptyState bordered positive icon="✅" title="All clear" description="No locked accounts or pending reviews." />
  );
}
