/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/command/command.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Command } = scope;
  return (
<Command trigger />
  );
}
