/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/command/command.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Command } = scope;
  return (
<Command
  defaultActive={0}
  placeholder="Type a command..."
  groups={[
    { heading: "Actions", items: [
      { label: "New File", icon: "📄", shortcut: "Ctrl+N" },
      { label: "Open File", icon: "📂", shortcut: "Ctrl+O" },
      { label: "Save", icon: "💾", shortcut: "Ctrl+S" }
    ] },
    { heading: "Navigation", items: [
      { label: "Go to Dashboard", icon: "▸" },
      { label: "Go to Settings", icon: "▸" }
    ] }
  ]}
/>
  );
}
