/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Alert, Button } = scope;
  return (
<Alert warning icon="⚠" title="Action required" description="Your trial expires in 3 days. Upgrade to keep your projects.">
  <View style={{ marginTop: 12, flexDirection: "row", gap: 8 }}>
    <Button primary small>Upgrade plan</Button>
  </View>
</Alert>
  );
}
