/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/chip/chip.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Icon, Row, Chip } = scope;
  return (
<Row snug wrap alignCenter>
  <Chip blue onRemove={() => {}}>Role: Admin</Chip>
  <Chip green onRemove={() => {}}>Status: Active</Chip>
  <Chip outline onPress={() => {}} icon={<Icon plus size={14} />}>Add filter</Chip>
</Row>
  );
}
