/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/chip/chip.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Icon, Chip } = scope;
  return (
<Chip primary icon={<Icon check primaryForeground size={14} />}>Verified</Chip>
  );
}
