/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/collapsible/collapsible.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Text, Collapsible } = scope;
  return (
<Collapsible title="Returns policy">
  <Text>30-day returns, no questions asked. Refunds post within 5 business days.</Text>
</Collapsible>
  );
}
