/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/collapsible/collapsible.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Text, Collapsible } = scope;
  return (
<Collapsible
  trigger={<Text>Order #1024 — 3 items</Text>}
  defaultOpen
>
  <Text>Wireless mouse, USB-C cable, laptop stand. Estimated total $84.00.</Text>
</Collapsible>
  );
}
