/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/field/field.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Text } = scope;
  return (
<View style={{ maxWidth: 400, flexDirection: "column", gap: 4 }}>
  <Text style={{ fontSize: 14, lineHeight: 20 }}>
    <Text style={{ fontWeight: "600" }}>Name:</Text>
     Rachel Chen
  </Text>
  <Text style={{ fontSize: 14, lineHeight: 20 }}>
    <Text style={{ fontWeight: "600" }}>Role:</Text>
     Admin
  </Text>
</View>
  );
}
