/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/field/field.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Field } = scope;
  return (
<Field
  rows={[
    { label: "Status", status: "Active" },
    { label: "Plan", badge: "Pro" },
    { label: "Token", value: "sk_live_a8f2...c9e1", mono: true, copyValue: "sk_live_a8f2c9e1" },
    { label: "Members", avatars: [
      { src: "/rachel-chen.jpg", name: "RC" },
      { name: "AJ" }
    ], overflow: 3 }
  ]}
  style={{ maxWidth: 400 }}
/>
  );
}
