/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/field/field.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Field } = scope;
  return (
<Field
  rows={[
    { label: "Client ID", value: "clt_8f2a9b4c7e1d", mono: true },
    { label: "Created", value: "2026-05-24T14:32:00Z", mono: true },
    { label: "Fingerprint", value: "sha256:xK9v...", mono: true }
  ]}
  style={{ maxWidth: 400 }}
/>
  );
}
