/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Avatar } = scope;
  return (
<View style={{ flexDirection: "row", alignItems: "center" }}>
  <Avatar small ring name="AO" />
  <Avatar small ring name="RC" style={{ marginLeft: -10 }} />
  <Avatar small ring name="LB" style={{ marginLeft: -10 }} />
  <Avatar small ring name="KT" style={{ marginLeft: -10 }} />
  <Text style={{ marginLeft: 6, fontSize: 12, lineHeight: 16, color: tokens["muted-foreground"] }}>+12</Text>
</View>
  );
}
