/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/data-table/data-table.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Card, DataTable, Divider, Input, Typography, Row } = scope;
  return (
<Card flat flush style={{ overflow: "hidden", maxWidth: 520 }}>
  <Row snug alignCenter between pad>
    <Input small narrow placeholder="Search users..." />
    <Button outline small>Export</Button>
  </Row>
  <Divider />
  <DataTable columns={["Name", "Email"]} rows={[
    ["Alice Johnson", "alice@example.com"],
    ["Bob Smith", "bob@example.com"],
    ["Rachel Chen", "rachel@example.com"]
  ]} />
  <Divider />
  <Row alignCenter between pad>
    <Typography small muted>Showing 1–3 of 142</Typography>
    <Row tight>
      <Button outline small disabled>«</Button>
      <Button outline small>»</Button>
    </Row>
  </Row>
</Card>
  );
}
