/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/data-table/data-table.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, DataTable } = scope;
  return (
<Stateful initial={[
  ["/pricing", "12,480"],
  ["/docs", "8,102"],
  ["/blog", "5,914"]
]}>
  {(rows, setRows) => (
    <DataTable
      columns={["Page", { label: "Visits", numeric: true }]}
      rows={rows}
      bordered
      inlineEdit
      onCellCommit={(i, c, next) =>
        setRows(rows.map((row, r) => (r === i ? row.map((cell, ci) => (ci === c ? next : cell)) : row)))
      }
    />
  )}
</Stateful>
  );
}
