/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/data-table/data-table.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Avatar, Badge, DataTable, Typography, Row } = scope;
  return (
<DataTable
  columns={[
    { label: "Member", sortValue: (_cell, _row, i) => ["Alice Johnson", "Bob Smith", "Rachel Chen"][i] },
    "Role",
    { label: "Status", centered: true, width: 120 }
  ]}
  rows={[
    [
      <Row snug alignCenter>
        <Avatar small name="Alice Johnson" />
        <Typography small medium>Alice Johnson</Typography>
      </Row>,
      "Admin",
      <Badge success>Active</Badge>
    ],
    [
      <Row snug alignCenter>
        <Avatar small name="Bob Smith" />
        <Typography small medium>Bob Smith</Typography>
      </Row>,
      "Editor",
      <Badge neutral>Invited</Badge>
    ],
    [
      <Row snug alignCenter>
        <Avatar small name="Rachel Chen" />
        <Typography small medium>Rachel Chen</Typography>
      </Row>,
      "Admin",
      <Badge success>Active</Badge>
    ]
  ]}
  bordered
  sortable
/>
  );
}
