/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/data-table/data-table.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, DataTable } = scope;
  return (
<Stateful initial={[
  ["Alice Johnson", "alice@example.com", "Admin"],
  ["Bob Smith", "bob@example.com", "Editor"],
  ["Rachel Chen", "rachel@example.com", "Viewer"]
]}>
  {(rows, setRows) => (
    <DataTable
      columns={["Name", "Email", "Role"]}
      rows={rows}
      bordered
      onRowEdit={() => {}}
      onRowCommit={(i, cells) => setRows(rows.map((row, r) => (r === i ? cells.map(String) : row)))}
      onRowDelete={(i) => setRows(rows.filter((_row, r) => r !== i))}
    />
  )}
</Stateful>
  );
}
