/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/data-table/data-table.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { DataTable } = scope;
  return (
<DataTable
  columns={["Name", "Email", "Role", "Status"]}
  rows={[
    ["Alice Johnson", "alice@example.com", "Admin", "Active"],
    ["Bob Smith", "bob@example.com", "Editor", "Inactive"],
    ["Rachel Chen", "rachel@example.com", "Admin", "Active"]
  ]}
  bordered
  selectable
/>
  );
}
