/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/backdrop/backdrop.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Backdrop } = scope;
  return (
<View style={{ height: 220 }}>
  <Backdrop vivid energetic dense>
    <Backdrop.Particles
      field={Array.from({ length: 80 }, (_, i) => ({ x: ((i * 41) % 97) / 97, y: ((i * 23) % 89) / 89, r: 1.6 + ((i * 5) % 5) / 2, a: 0.8 + ((i * 7) % 10) / 50 }))}
      depth={1}
      sprite="spark"
    />
  </Backdrop>
</View>
  );
}
