/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/backdrop/backdrop.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Backdrop } = scope;
  return (
<View style={{ height: 220 }}>
  <Backdrop subtle calm>
    <Backdrop.Particles
      field={Array.from({ length: 80 }, (_, i) => ({ x: ((i * 41) % 97) / 97, y: ((i * 23) % 89) / 89, r: 0.7 + ((i * 5) % 5) / 4, a: 0.3 + ((i * 7) % 10) / 15 }))}
      depth={0}
      twinkle
    />
  </Backdrop>
</View>
  );
}
