/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/backdrop/backdrop.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Backdrop } = scope;
  return (
<View style={{ height: 220 }}>
  <Backdrop energetic>
    {[0, 0.25, 0.5, 0.75].map((phase) => (
      <Backdrop.Particles
        key={phase}
        field={Array.from({ length: 40 }, (_, i) => ({
          x: 0.5 + Math.cos(i * 2.4) * (0.05 + ((i * 11) % 40) / 100),
          y: 0.5 + Math.sin(i * 2.4) * (0.05 + ((i * 11) % 40) / 100),
          r: 0.8 + ((i * 7) % 5) / 3,
          a: 0.4 + ((i * 3) % 10) / 16,
        }))}
        depth={1}
        phase={phase}
        sprite="halo"
        bloom
      />
    ))}
  </Backdrop>
</View>
  );
}
