/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/listbox/listbox.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Listbox } = scope;
  return (
<Listbox bordered style={{ width: 192 }} items={[
    { label: "Yes", selected: true },
    { label: "No" }
  ]} />
  );
}
