/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/empty-state/empty-state.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, DataTable, EmptyState, Column } = scope;
  return (
<Card flat style={{ overflow: "hidden" }}>
  <DataTable columns={["Name", "Email", "Role", "Status"]} rows={[]} />
  <Column alignCenter padLoose>
    <EmptyState bordered icon="🔍" title="No results found" description="Try adjusting your search filters." actionLabel="Clear filters" />
  </Column>
</Card>
  );
}
