/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/empty-state/empty-state.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, EmptyState } = scope;
  return (
<EmptyState
  icon="✅"
  title="All clear"
  description="No locked accounts or pending reviews."
  actionLabel="View history"
  positive
  bordered
/>
  );
}
