/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/empty-state/empty-state.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, EmptyState, Icon } = scope;
  return (
<EmptyState
  icon={<Icon bell />}
  title="All caught up"
  description="No new notifications."
  actionLabel="View archive"
  bordered
/>
  );
}
