/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/grid/grid.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Typography, Grid } = scope;
  return (
<Grid minTileWidth={220} columns={3}>
  <Card padded>
    <Typography medium>Overview</Typography>
  </Card>
  <Card padded>
    <Typography medium>Deploys</Typography>
  </Card>
  <Card padded>
    <Typography medium>Alerts</Typography>
  </Card>
</Grid>
  );
}
