/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/grid/grid.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Typography, Row } = scope;
  return (
<Row wrap snug>
  <Card padded style={{ width: "31%" }}>
    <Typography medium>Overview</Typography>
  </Card>
  <Card padded style={{ width: "31%" }}>
    <Typography medium>Deploys</Typography>
  </Card>
  <Card padded style={{ width: "31%" }}>
    <Typography medium>Alerts</Typography>
  </Card>
</Row>
  );
}
