/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/number-input/number-input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { NumberInput, Typography, Column } = scope;
  return (
<Column snug>
  <Typography small medium>Quantity</Typography>
  <NumberInput defaultValue={1} min={1} max={9} onChange={() => {}} />
</Column>
  );
}
