/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/number-input/number-input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, NumberInput } = scope;
  return (
<View style={{ gap: 8 }}>
  <Text style={{ fontSize: 14, lineHeight: 20, fontWeight: "500", color: tokens.foreground }}>Quantity</Text>
  <NumberInput value={1} min={1} max={9} onChange={() => {}} />
</View>
  );
}
