/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/number-input/number-input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { NumberInput } = scope;
  return (
<NumberInput defaultValue={1} onChange={() => {}} />
  );
}
