/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/number-input/number-input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { NumberInput, Row } = scope;
  return (
<Row alignCenter relaxed>
  <NumberInput small value={2} min={0} max={10} onChange={() => {}} />
  <NumberInput value={2} min={0} max={10} onChange={() => {}} />
  <NumberInput large value={2} min={0} max={10} onChange={() => {}} />
</Row>
  );
}
