/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/number-input/number-input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, NumberInput } = scope;
  return (
<View style={{ flexDirection: "row", alignItems: "center", gap: 16 }}>
  <NumberInput small value={2} min={0} max={10} onChange={() => {}} />
  <NumberInput value={2} min={0} max={10} onChange={() => {}} />
  <NumberInput large value={2} min={0} max={10} onChange={() => {}} />
</View>
  );
}
