/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Typography } = scope;
  return (
<View>
  <Typography body>Save changes</Typography>
  <Typography small style={{ marginTop: 2 }}>Last saved 2 minutes ago.</Typography>
</View>
  );
}
