/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Typography } = scope;
  return (
<View style={{ gap: 4 }}>
  <Typography h1>Billing</Typography>
  <Typography h1>Invoices</Typography>
</View>
  );
}
