/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Typography } = scope;
  return (
<Typography body style={{ maxWidth: 340 }}>
  Payment due May 31. 
  <Typography body style={{ color: tokens.primary, textDecorationLine: "underline" }}>View invoices</Typography>
</Typography>
  );
}
