/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Typography } = scope;
  return (
<View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 16 }}>
  <Typography small>Request ID</Typography>
  <Typography mono>req_8f2c10ab</Typography>
</View>
  );
}
