/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Typography } = scope;
  return (
<View>
  <Typography h1>Settings</Typography>
  <Typography h4 style={{ marginTop: 16 }}>Profile</Typography>
</View>
  );
}
