/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/grid-lists/grid-lists.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, GridList } = scope;
  return (
<GridList
  items={[
    { title: "Rachel Chen", subtitle: "Engineering Lead", avatar: "/rachel-chen.jpg", actions: [
      { label: "Message", outline: true },
      { label: "View", ghost: true }
    ] },
    { title: "Ada Lovelace", subtitle: "Staff Engineer", avatar: "/ada-lovelace.jpg", actions: [
      { label: "Message", outline: true },
      { label: "View", ghost: true }
    ] },
    { title: "Kevin Turner", subtitle: "Product Designer", avatar: "KT", actions: [
      { label: "Message", outline: true },
      { label: "View", ghost: true }
    ] }
  ]}
  cols2
/>
  );
}
