/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/grid-lists/grid-lists.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, GridList, Typography, Column } = scope;
  return (
<Stateful initial="">
  {(opened, setOpened) => (
    <Column snug>
      <GridList
        onPressItem={(index) => setOpened(["Rachel Chen", "Ada Lovelace", "Kevin Turner"][index])}
        items={[
          { title: "Rachel Chen", subtitle: "Engineering Lead", avatar: "RC", badge: "Active" },
          { title: "Ada Lovelace", subtitle: "Staff Engineer", avatar: "AL", badge: "Active" },
          { title: "Kevin Turner", subtitle: "Product Designer", avatar: "KT", badge: "Away" }
        ]}
        cols3
      />
      <Typography muted>{opened === "" ? "Tap a card to open a profile" : `Opened ${opened}`}</Typography>
    </Column>
  )}
</Stateful>
  );
}
