/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/radio/radio.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Radio, Typography, Row, Column } = scope;
  return (
<Column snug>
  <Row snug alignStart>
    <Radio checked />
    <Column>
      <Typography small medium>Pro</Typography>
      <Typography tiny muted>For growing teams that need more control.</Typography>
    </Column>
  </Row>
</Column>
  );
}
