/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/radio/radio.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Radio, Typography, Column } = scope;
  return (
<Column snug>
  <Typography small semibold>Plan</Typography>
  <Radio>Hobby</Radio>
  <Radio checked>Pro</Radio>
  <Radio>Enterprise</Radio>
</Column>
  );
}
