/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/radio/radio.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Radio, Typography, Row, Column } = scope;
  return (
<Row snug>
  <Column fill>
    <Card padded selected>
      <Column snug>
        <Radio checked />
        <Typography small semibold>Pro</Typography>
        <Typography tiny muted>For growing teams.</Typography>
      </Column>
    </Card>
  </Column>
  <Column fill>
    <Card padded>
      <Column snug>
        <Radio />
        <Typography small semibold>Enterprise</Typography>
        <Typography tiny muted>Advanced security.</Typography>
      </Column>
    </Card>
  </Column>
</Row>
  );
}
