/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/radio/radio.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Radio } = scope;
  return (
<Radio checked description="For growing teams that need more control.">Pro</Radio>
  );
}
