/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/radio/radio.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Radio, Row } = scope;
  return (
<Row loose wrap>
  <Radio checked small>Hobby</Radio>
  <Radio small>Pro</Radio>
  <Radio small>Enterprise</Radio>
</Row>
  );
}
