/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/radio/radio.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Radio } = scope;
  return (
<Radio checked small>Pro, for growing teams that need more control.</Radio>
  );
}
