/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/drawer/drawer.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Drawer } = scope;
  return (
<Drawer trigger="Open navigation" left width={260}>
  <View style={{ padding: 20, gap: 10 }}>
    <Text style={{ fontSize: 15, fontWeight: "600", color: tokens.foreground }}>Navigation</Text>
    <Text style={{ fontSize: 14, color: tokens["muted-foreground"] }}>Home</Text>
    <Text style={{ fontSize: 14, color: tokens["muted-foreground"] }}>Components</Text>
  </View>
</Drawer>
  );
}
