/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/drawer/drawer.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Drawer, Typography, Column } = scope;
  return (
<Drawer trigger="Open navigation" left width={260}>
  <Column padLoose snug>
    <Typography lead semibold>Navigation</Typography>
    <Typography small muted>Home</Typography>
    <Typography small muted>Components</Typography>
  </Column>
</Drawer>
  );
}
