/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/drawer/drawer.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Button, Drawer, Typography, Column } = scope;
  return (
<Drawer trigger="Right drawer" right width={240}>
  <Column padLoose snug>
    <Typography lead semibold>Details</Typography>
    <Typography small muted>A full-height panel on the right.</Typography>
    <Button primary block onPress={() => {}}>View full details</Button>
  </Column>
</Drawer>
  );
}
