/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/drawer/drawer.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Drawer } = scope;
  return (
<Drawer trigger="Bottom sheet" bottom>
  <View style={{ padding: 20, gap: 10 }}>
    <Text style={{ fontSize: 15, fontWeight: "600", color: tokens.foreground }}>Actions</Text>
    <Text style={{ fontSize: 14, color: tokens["muted-foreground"] }}>Share</Text>
    <Text style={{ fontSize: 14, color: tokens["muted-foreground"] }}>Duplicate</Text>
    <Text style={{ fontSize: 14, color: tokens["muted-foreground"] }}>Delete</Text>
  </View>
</Drawer>
  );
}
