/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/drawer/drawer.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Drawer, Typography, Column } = scope;
  return (
<Drawer trigger="Open menu" left width={260}>
  <Column padLoose cozy>
    <Typography lead semibold>Menu</Typography>
    <Button ghost block onPress={() => {}}>Home</Button>
    <Button ghost block onPress={() => {}}>Components</Button>
    <Button ghost block onPress={() => {}}>Settings</Button>
  </Column>
</Drawer>
  );
}
