/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/drawer/drawer.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Drawer, Typography, Column } = scope;
  return (
<Drawer trigger="Bottom sheet" bottom>
  <Column padLoose snug>
    <Typography lead semibold>Actions</Typography>
    <Button ghost block onPress={() => {}}>Share</Button>
    <Button ghost block onPress={() => {}}>Duplicate</Button>
    <Button destructive block onPress={() => {}}>Delete</Button>
  </Column>
</Drawer>
  );
}
