/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/input/input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Input, Typography, Column } = scope;
  return (
<Column snug style={{ maxWidth: 320 }}>
  <Typography small medium>Storage</Typography>
  <Input value="1024" suffix="GB" />
</Column>
  );
}
