/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/input/input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Textarea, Typography, Column } = scope;
  return (
<Column snug style={{ maxWidth: 320 }}>
  <Typography small medium>Notes</Typography>
  <Textarea rows={4} value="Describe the change in enough detail that a teammate could follow it…" />
</Column>
  );
}
