/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/input/input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Select } = scope;
  return (
<Select label="Email notifications" options={["On", "Off"]} value="On" style={{ maxWidth: 320 }} />
  );
}
