/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/input/input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Input, Column } = scope;
  return (
<Column snug>
  <Input narrow placeholder="Narrow (240px)" />
  <Input placeholder="Standard (320px)" />
  <Input wide placeholder="Wide (480px)" />
  <Input block placeholder="Block (fills the container)" />
</Column>
  );
}
