/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/input/input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Select, Typography, Column } = scope;
  return (
<Column snug>
  <Select label="Status" defaultValue="Active" options={["Active", "Inactive", "Pending"]} />
  <Typography tiny muted>We'll use this for account recovery.</Typography>
</Column>
  );
}
