/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/steps/steps.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Steps } = scope;
  return (
<View style={{ maxWidth: 320 }}>
  <Steps progress current={0} steps={[]} label="Setup progress" value={68} />
</View>
  );
}
