/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/select/select.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Field, Select, Row, Column } = scope;
  return (
<Row alignEnd cozy style={{ maxWidth: 420 }}>
  <Column fill>
    <Field label="City" value="Austin" />
  </Column>
  <Column fill>
    <Select label="State" value="Texas" options={["Texas", "Oregon"]} />
  </Column>
</Row>
  );
}
