/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/select/select.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Select } = scope;
  return (
<Select large label="Plan" value="Starter" options={["Starter", "Pro", "Enterprise"]} style={{ maxWidth: 320 }} />
  );
}
