/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/stepper/stepper.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Stepper } = scope;
  return (
<View style={{ maxWidth: 320 }}>
  <Stepper vertical current={1} steps={[
    { label: "Account created" },
    { label: "Profile setup" },
    { label: "Team invite" },
    { label: "Done" }
  ]} />
</View>
  );
}
