/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/stepper/stepper.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stepper } = scope;
  return (
<Stepper
  steps={[
    { label: "Account", description: "Email verified and password set." },
    { label: "Profile", description: "Add your name and avatar." },
    { label: "Review", description: "Invite collaborators to your workspace." },
    { label: "Done", description: "You're all set." }
  ]}
  current={1}
  onStepPress={() => {}}
  value={68}
  label="Setup progress"
/>
  );
}
