/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/view/view.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text } = scope;
  return (
<View style={{ width: 240, padding: 16, borderRadius: 10, borderWidth: 1, borderColor: tokens.border, backgroundColor: tokens.card }}>
  <Text style={{ color: tokens.foreground }}>A look-alike surface</Text>
</View>
  );
}
