/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/view/view.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Icon, Typography, Row, Emblem } = scope;
  return (
<Row cozy alignCenter>
  <Emblem primary><Icon shield /></Emblem>
  <Typography semibold>Semantic arrangement</Typography>
</Row>
  );
}
