/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/view/view.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, alpha, View, Text } = scope;
  return (
<View style={{ flexDirection: "row", alignItems: "center", gap: 12 }}>
  <View style={{ width: 32, height: 32, borderRadius: 8, backgroundColor: alpha(tokens.primary, 0.12) }} />
  <Text style={{ color: tokens.foreground, fontWeight: "600" }}>Hand-rolled arrangement</Text>
</View>
  );
}
