/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/view/view.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text } = scope;
  return (
<View style={{ flexDirection: "row", alignItems: "center", gap: 12 }}>
  <View style={{ width: 40, height: 40, borderRadius: 8, backgroundColor: tokens.primary }} />
  <Text style={{ color: tokens.foreground, fontWeight: "600" }}>Two Views in a row</Text>
</View>
  );
}
