/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/kbd/kbd.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Text, Kbd } = scope;
  return (
<View style={{ flexDirection: "row", alignItems: "center", gap: 4 }}>
  <Text style={{ fontSize: 14, lineHeight: 20 }}>Press</Text>
  <Kbd>Ctrl</Kbd>
  <Kbd>K</Kbd>
  <Text style={{ fontSize: 14, lineHeight: 20 }}>to search.</Text>
</View>
  );
}
