/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/kbd/kbd.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Text } = scope;
  return (
<Text style={{ fontSize: 14, lineHeight: 20 }}>Press Ctrl+K to search.</Text>
  );
}
