/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/charts/charts.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Typography, Row, Column, Sparkline } = scope;
  return (
<Card padded style={{ maxWidth: 200 }}>
  <Column snug>
    <Column tight>
      <Typography tiny>Tokens issued</Typography>
      <Row between baseline>
        <Typography h3>4,847</Typography>
        <Typography tiny primary>+12%</Typography>
      </Row>
    </Column>
    <Sparkline tall values={[6, 8, 12, 10, 16, 20, 18, 25, 23, 29]} style={{ width: 180 }} />
  </Column>
</Card>
  );
}
