/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/charts/charts.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Sparkline } = scope;
  return (
<Card padded style={{ maxWidth: 200 }}>
  <Sparkline tall values={[45, 60, 35, 70, 55, 80, 95]} style={{ width: 160 }} />
</Card>
  );
}
