/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/charts/charts.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { LineChart } = scope;
  return (
<LineChart
  title="Signups"
  labels={["Jan", "Feb", "Mar", "Apr", "May", "Jun"]}
  series={[
    { label: "Web", values: [120, 180, 150, 240, 300, 280] },
    { label: "Mobile", values: [60, 90, 140, 160, 220, 260] }
  ]}
  curved
  dots
  style={{ maxWidth: 560 }}
/>
  );
}
