/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/sidebar/sidebar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Tabs } = scope;
  return (
<Tabs underline active={0} tabs={["Overview", "Sessions", "Audit log"]} />
  );
}
