/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/sidebar/sidebar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Typography } = scope;
  return (
<View style={{ width: 420, maxWidth: "100%" }}>
  <Typography h4>Users</Typography>
  <Typography muted style={{ marginTop: 4 }}>Manage your team members.</Typography>
</View>
  );
}
