/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/depth-chart/depth-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { DepthChart } = scope;
  return (
<DepthChart
  title="OLY order book"
  bids={[
    { price: 191.2, size: 120 },
    { price: 191, size: 340 },
    { price: 190.8, size: 260 },
    { price: 190.5, size: 480 },
    { price: 190.2, size: 380 }
  ]}
  asks={[
    { price: 191.6, size: 150 },
    { price: 191.9, size: 290 },
    { price: 192.1, size: 310 },
    { price: 192.4, size: 520 },
    { price: 192.8, size: 300 }
  ]}
  style={{ maxWidth: 560 }}
/>
  );
}
