/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Avatar } = scope;
  return (
<View style={{ flexDirection: "row", alignItems: "center" }}>
  <Avatar small ring name="AO" />
  <Avatar small ring name="RC" style={{ marginLeft: -10 }} />
  <Avatar small ring name="LB" style={{ marginLeft: -10 }} />
  <Avatar small ring name="KT" style={{ marginLeft: -10 }} />
  <Avatar small ring name="JD" style={{ marginLeft: -10 }} />
  <Avatar small ring name="MA" style={{ marginLeft: -10 }} />
  <Avatar small ring name="AL" style={{ marginLeft: -10 }} />
  <Avatar small ring name="SK" style={{ marginLeft: -10 }} />
</View>
  );
}
