/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { AvatarMenu } = scope;
  return (
<AvatarMenu name="Ada Lovelace" email="ada.lovelace@example.com" src="/ada-lovelace.jpg" items={[
    { label: "Profile", icon: "user", disabled: true },
    { label: "Settings", icon: "settings", shortcut: "⌘,", disabled: true },
    { label: "Sign out", icon: "logOut", destructive: true, separatorBefore: true, disabled: true }
  ]} />
  );
}
