/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { AvatarMenu } = scope;
  return (
<AvatarMenu name="Kira Tanaka" email="kira.tanaka@example.com" src="/kira-tanaka.jpg" items={[
    { label: "Profile", icon: "user" },
    { label: "Sign out", icon: "logOut" },
    { label: "Billing", icon: "creditCard" },
    { label: "Settings", icon: "settings", shortcut: "⌘," }
  ]} />
  );
}
