/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Avatar, Typography, Row, Column } = scope;
  return (
<Row cozy alignCenter>
  <Avatar src="/ada-lovelace.jpg" name="AL" />
  <Column>
    <Typography small semibold>Ada Lovelace</Typography>
    <Typography tiny muted>admin@example.com</Typography>
  </Column>
</Row>
  );
}
