/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, Avatar, Icon, Typography, Row } = scope;
  return (
<Row snug alignCenter style={{ borderRadius: 9999, borderWidth: 1, borderColor: tokens.border, backgroundColor: tokens.card, paddingVertical: 4, paddingLeft: 4, paddingRight: 10 }}>
  <Avatar small src="/marcus-allen.jpg" name="MA" />
  <Typography small medium>admin@example.com</Typography>
  <Icon chevronDown muted size={12} />
</Row>
  );
}
