/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Avatar, Icon, Chip } = scope;
  return (
<Chip outline icon={<Avatar small src="/marcus-allen.jpg" name="MA" />} trailing={<Icon chevronDown muted size={12} />}>admin@example.com</Chip>
  );
}
