/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { AvatarMenu } = scope;
  return (
<AvatarMenu compact name="Noor Park" email="noor.park@example.com" src="/noor-park.jpg" items={[
    { label: "Profile", icon: "user" },
    { label: "Settings", icon: "settings", shortcut: "⌘," },
    { label: "Sign out", icon: "logOut", destructive: true, separatorBefore: true }
  ]} />
  );
}
