/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { MediaObject } = scope;
  return (
<MediaObject compact center src="/ada-lovelace.jpg" title="Ada Lovelace" description="admin@example.com" />
  );
}
