/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Avatar } = scope;
  return (
<View style={{ flexDirection: "row", alignItems: "center" }}>
  <Avatar ring src="/rachel-chen.jpg" name="RC" />
  <Avatar ring src="/liang-bao.jpg" name="LB" style={{ marginLeft: -12 }} />
  <Avatar ring src="/marcus-allen.jpg" name="LB" style={{ marginLeft: -12 }} />
  <Avatar ring src="/kira-tanaka.jpg" name="KT" style={{ marginLeft: -12 }} />
</View>
  );
}
