/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Avatar, Row } = scope;
  return (
<Row relaxed alignCenter>
  <Avatar small src="/ada-lovelace.jpg" name="AL" />
  <Avatar src="/marcus-allen.jpg" name="MA" />
  <Avatar large src="/rachel-chen.jpg" name="RC" />
</Row>
  );
}
