/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Avatar, AvatarGroup } = scope;
  return (
<AvatarGroup small max={4}>
  <Avatar src="/rachel-chen.jpg" name="RC" />
  <Avatar src="/liang-bao.jpg" name="LB" />
  <Avatar src="/marcus-allen.jpg" name="MA" />
  <Avatar src="/kira-tanaka.jpg" name="KT" />
  <Avatar src="/ada-lovelace.jpg" name="AL" />
  <Avatar src="/grace-hopper.jpg" name="GH" />
  <Avatar src="/noor-park.jpg" name="NP" />
</AvatarGroup>
  );
}
