/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Avatar, Typography, Row, Column } = scope;
  return (
<Row relaxed alignCenter>
  <Avatar src="/rachel-chen.jpg" name="RC" />
  <Column>
    <Typography lead semibold>Rachel Chen</Typography>
    <Typography small muted>rachel.chen@example.com</Typography>
  </Column>
</Row>
  );
}
