/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/swatch/swatch.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, Swatch, Row } = scope;
  return (
<Row snug alignCenter>
  <Swatch circle color={tokens.primary} value="--primary">primary</Swatch>
  <Swatch circle color={tokens.accent} value="--accent">accent</Swatch>
</Row>
  );
}
