/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/swatch/swatch.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, Swatch, Column } = scope;
  return (
<Column snug>
  <Swatch block small color={tokens.primary} value="--primary">primary</Swatch>
  <Swatch block small color={tokens.secondary} value="--secondary">secondary</Swatch>
</Column>
  );
}
