/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/swatch/swatch.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, Swatch, Row } = scope;
  return (
<Row snug alignStart>
  <Swatch small color={tokens.primary} value="--primary">primary</Swatch>
  <Swatch color={tokens.success} value="--success">success</Swatch>
  <Swatch large color={tokens.destructive} value="--destructive">destructive</Swatch>
</Row>
  );
}
