/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Form } = scope;
  return (
<Form sidebar submitLabel="Save" style={{ maxWidth: 720 }} sections={[
    { title: "Personal info", fields: [
      { label: "Full name", value: "Rachel Chen" }
    ] },
    { title: "Billing", fields: [
      { label: "Card number", value: "•••• 4242" }
    ] }
  ]} />
  );
}
