/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/stacked-lists/stacked-lists.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { StackedList } = scope;
  return (
<StackedList items={[
    { name: "Rachel Chen", detail: "rachel.chen@example.com", initials: "RC" }
  ]} />
  );
}
