/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/stacked-lists/stacked-lists.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, StackedList } = scope;
  return (
<Stateful initial={[
  { id: "rachel", name: "Rachel Chen", detail: "rachel.chen@example.com" },
  { id: "ada", name: "Ada Lovelace", detail: "ada@example.com" },
]}>
  {(people, setPeople) => (
    <StackedList
      reorderable
      items={people}
      onReorder={({ fromIndex, toIndex }) => {
        const next = [...people];
        next.splice(toIndex, 0, ...next.splice(fromIndex, 1));
        setPeople(next);
      }}
    />
  )}
</Stateful>
  );
}
