/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/stacked-lists/stacked-lists.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, Button, StackedList } = scope;
  return (
<Stateful initial={[
  { id: "rachel", name: "Rachel Chen", detail: "Engineering Lead" },
  { id: "ada", name: "Ada Lovelace", detail: "Staff Engineer" },
]}>
  {(people, setPeople) => (
    <StackedList
      card
      title="Team members"
      action={<Button ghost small onPress={() => setPeople([...people, { id: `invite-${people.length}`, name: "Kevin Turner", detail: "Pending invite" }])}>Invite</Button>}
      items={people}
    />
  )}
</Stateful>
  );
}
