/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/stacked-lists/stacked-lists.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { StackedList } = scope;
  return (
<StackedList
  items={[
    { name: "Rachel Chen", detail: "rachel.chen@example.com", meta: "admin" },
    { name: "Ada Lovelace", detail: "ada@example.com", meta: "editor" },
    { name: "Kevin Turner", detail: "kevin@example.com", meta: "viewer" }
  ]}
/>
  );
}
