/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/stacked-lists/stacked-lists.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { StackedList } = scope;
  return (
<StackedList
  items={[
    { name: "Kratos", detail: "Identity", badge: "Healthy", success: true },
    { name: "Hydra", detail: "OAuth2", badge: "Degraded", warning: true },
    { name: "Postgres", detail: "Database", badge: "Down", error: true },
  ]}
/>
  );
}
