/**
 * Generates the Canvas layout utility layer as static, plain-CSS files under
 * styles/utilities/. Run via `bun run generate-utilities`.
 *
 * Why a generator: the utility set is ~140 base classes, each repeated across 5
 * responsive breakpoints (~840 rules). Hand-maintaining that is error-prone. This
 * script is an authoring-time tool (like the other scripts/*.ts); the OUTPUT it
 * commits is ordinary CSS, so consumers still need no build step.
 *
 * Output is deterministic: groups in config order, base rules before responsive,
 * breakpoints ascending. Re-running produces a zero git diff. CI enforces that the
 * committed files match what this script produces.
 */
import { mkdir, writeFile, readFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const STYLES_DIR = join(ROOT, "styles");
const OUT_DIR = join(STYLES_DIR, "utilities");

const BANNER =
  "/* AUTO-GENERATED by scripts/generate-utilities.ts. Do not edit by hand; run: bun run generate-utilities */";

// Mobile-first min-width breakpoints. Order is the emit order (ascending).
const BREAKPOINTS: Array<[string, number]> = [
  ["sm", 640],
  ["md", 768],
  ["lg", 1024],
  ["xl", 1280],
  ["2xl", 1536],
];

// Backs the token-referenced gap utilities. Each value must exist as --space-<v>
// in styles/tokens/spacing.css (asserted below before any file is written).
const SPACE_SCALE = [
  "0", "px", "0-5", "1", "1-5", "2", "2-5", "3", "4", "5", "6", "8", "10", "12", "16",
];

interface Rule {
  cls: string; // logical class name, unescaped (e.g. "flex", "w-1/2", "gap-0-5")
  decl: string; // declaration body, no trailing semicolon (e.g. "display:flex")
}

interface Group {
  file: string; // output filename stem under styles/utilities/
  responsive: boolean; // emit sm/md/lg/xl/2xl variants?
  rules: Rule[];
}

function span(n: number): Rule {
  return { cls: `col-span-${n}`, decl: `grid-column:span ${n} / span ${n}` };
}
function cols(n: number): Rule {
  return { cls: `grid-cols-${n}`, decl: `grid-template-columns:repeat(${n}, minmax(0, 1fr))` };
}

// Token-backed gap rules, generated from the spacing scale.
const gapRules: Rule[] = [];
for (const v of SPACE_SCALE) {
  gapRules.push({ cls: `gap-${v}`, decl: `gap:var(--space-${v})` });
}
for (const v of SPACE_SCALE) {
  gapRules.push({ cls: `gap-x-${v}`, decl: `column-gap:var(--space-${v})` });
}
for (const v of SPACE_SCALE) {
  gapRules.push({ cls: `gap-y-${v}`, decl: `row-gap:var(--space-${v})` });
}

const GROUPS: Group[] = [
  {
    file: "display",
    responsive: true,
    rules: [
      { cls: "block", decl: "display:block" },
      { cls: "inline-block", decl: "display:inline-block" },
      { cls: "inline", decl: "display:inline" },
      { cls: "flex", decl: "display:flex" },
      { cls: "inline-flex", decl: "display:inline-flex" },
      { cls: "grid", decl: "display:grid" },
      { cls: "inline-grid", decl: "display:inline-grid" },
      { cls: "hidden", decl: "display:none" },
    ],
  },
  {
    file: "flexbox",
    responsive: true,
    rules: [
      { cls: "flex-row", decl: "flex-direction:row" },
      { cls: "flex-row-reverse", decl: "flex-direction:row-reverse" },
      { cls: "flex-col", decl: "flex-direction:column" },
      { cls: "flex-col-reverse", decl: "flex-direction:column-reverse" },
      { cls: "flex-wrap", decl: "flex-wrap:wrap" },
      { cls: "flex-wrap-reverse", decl: "flex-wrap:wrap-reverse" },
      { cls: "flex-nowrap", decl: "flex-wrap:nowrap" },
      { cls: "flex-1", decl: "flex:1 1 0%" },
      { cls: "flex-auto", decl: "flex:1 1 auto" },
      { cls: "flex-initial", decl: "flex:0 1 auto" },
      { cls: "flex-none", decl: "flex:none" },
      { cls: "grow", decl: "flex-grow:1" },
      { cls: "grow-0", decl: "flex-grow:0" },
      { cls: "shrink", decl: "flex-shrink:1" },
      { cls: "shrink-0", decl: "flex-shrink:0" },
      { cls: "justify-start", decl: "justify-content:flex-start" },
      { cls: "justify-end", decl: "justify-content:flex-end" },
      { cls: "justify-center", decl: "justify-content:center" },
      { cls: "justify-between", decl: "justify-content:space-between" },
      { cls: "justify-around", decl: "justify-content:space-around" },
      { cls: "justify-evenly", decl: "justify-content:space-evenly" },
      { cls: "items-start", decl: "align-items:flex-start" },
      { cls: "items-end", decl: "align-items:flex-end" },
      { cls: "items-center", decl: "align-items:center" },
      { cls: "items-baseline", decl: "align-items:baseline" },
      { cls: "items-stretch", decl: "align-items:stretch" },
      { cls: "content-start", decl: "align-content:flex-start" },
      { cls: "content-end", decl: "align-content:flex-end" },
      { cls: "content-center", decl: "align-content:center" },
      { cls: "content-between", decl: "align-content:space-between" },
      { cls: "content-around", decl: "align-content:space-around" },
      { cls: "content-evenly", decl: "align-content:space-evenly" },
      { cls: "self-auto", decl: "align-self:auto" },
      { cls: "self-start", decl: "align-self:flex-start" },
      { cls: "self-end", decl: "align-self:flex-end" },
      { cls: "self-center", decl: "align-self:center" },
      { cls: "self-stretch", decl: "align-self:stretch" },
    ],
  },
  {
    file: "grid",
    responsive: true,
    rules: [
      cols(1), cols(2), cols(3), cols(4), cols(5), cols(6),
      { cls: "grid-cols-none", decl: "grid-template-columns:none" },
      { cls: "grid-cols-auto-fit", decl: "grid-template-columns:repeat(auto-fit, minmax(min(100%, 16rem), 1fr))" },
      { cls: "grid-cols-auto-fill", decl: "grid-template-columns:repeat(auto-fill, minmax(min(100%, 16rem), 1fr))" },
      span(1), span(2), span(3), span(4), span(5), span(6),
      { cls: "col-span-full", decl: "grid-column:1 / -1" },
      { cls: "grid-flow-row", decl: "grid-auto-flow:row" },
      { cls: "grid-flow-col", decl: "grid-auto-flow:column" },
      { cls: "grid-flow-dense", decl: "grid-auto-flow:row dense" },
      { cls: "grid-flow-col-dense", decl: "grid-auto-flow:column dense" },
    ],
  },
  {
    file: "gap",
    responsive: true,
    rules: gapRules,
  },
  {
    file: "sizing",
    responsive: true,
    rules: [
      { cls: "w-full", decl: "width:100%" },
      { cls: "w-screen", decl: "width:100vw" },
      { cls: "w-auto", decl: "width:auto" },
      { cls: "w-min", decl: "width:min-content" },
      { cls: "w-max", decl: "width:max-content" },
      { cls: "w-fit", decl: "width:fit-content" },
      { cls: "w-1/2", decl: "width:50%" },
      { cls: "w-0", decl: "width:0px" },
      { cls: "h-full", decl: "height:100%" },
      { cls: "h-screen", decl: "height:100vh" },
      { cls: "h-auto", decl: "height:auto" },
      { cls: "h-min", decl: "height:min-content" },
      { cls: "h-max", decl: "height:max-content" },
      { cls: "h-fit", decl: "height:fit-content" },
      { cls: "h-dvh", decl: "height:100dvh" },
      { cls: "h-0", decl: "height:0px" },
      { cls: "min-w-0", decl: "min-width:0px" },
      { cls: "min-h-0", decl: "min-height:0px" },
      { cls: "max-w-full", decl: "max-width:100%" },
      { cls: "max-h-full", decl: "max-height:100%" },
    ],
  },
  {
    file: "position",
    responsive: true,
    rules: [
      { cls: "static", decl: "position:static" },
      { cls: "relative", decl: "position:relative" },
      { cls: "absolute", decl: "position:absolute" },
      { cls: "fixed", decl: "position:fixed" },
      { cls: "sticky", decl: "position:sticky" },
      { cls: "inset-0", decl: "top:0;right:0;bottom:0;left:0" },
      { cls: "top-0", decl: "top:0" },
      { cls: "right-0", decl: "right:0" },
      { cls: "bottom-0", decl: "bottom:0" },
      { cls: "left-0", decl: "left:0" },
    ],
  },
];

// Escape a utility class name so the authored selector matches the literal class
// attribute. Three cases:
//   - ":" is the breakpoint separator (md:flex)  -> "\:"
//   - "/" appears in fractional names (w-1/2)     -> "\/"
//   - a LEADING digit is invalid at the start of a CSS identifier, so the "2" in
//     "2xl:flex" must be escaped as a code point ("\32 " incl. trailing space),
//     otherwise the browser drops the whole rule.
function escapeClass(name: string): string {
  let out = "";
  for (let i = 0; i < name.length; i++) {
    const ch = name[i];
    if (i === 0 && ch >= "0" && ch <= "9") {
      out += "\\3" + ch + " ";
    } else if (ch === ":" || ch === "/") {
      out += "\\" + ch;
    } else {
      out += ch;
    }
  }
  return out;
}

function emitRule(cls: string, decl: string, indent: string): string {
  return `${indent}.${escapeClass(cls)} { ${decl}; }`;
}

function emitGroup(group: Group): string {
  const lines: string[] = [BANNER, "@layer canvas.utilities {"];

  for (const r of group.rules) {
    lines.push(emitRule(r.cls, r.decl, "  "));
  }

  if (group.responsive) {
    for (const [bp, min] of BREAKPOINTS) {
      lines.push("");
      lines.push(`  @media (min-width: ${min}px) {`);
      for (const r of group.rules) {
        lines.push(emitRule(`${bp}:${r.cls}`, r.decl, "    "));
      }
      lines.push("  }");
    }
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

async function main(): Promise<void> {
  // Guardrail: every gap utility must reference a token that actually exists.
  const spacingCss = await readFile(join(STYLES_DIR, "tokens", "spacing.css"), "utf-8");
  const definedSpace = new Set(
    [...spacingCss.matchAll(/--space-([\w-]+)\s*:/g)].map((m) => m[1]),
  );
  for (const v of SPACE_SCALE) {
    if (!definedSpace.has(v)) {
      throw new Error(
        `gap utility references --space-${v}, which is not defined in styles/tokens/spacing.css`,
      );
    }
  }

  await mkdir(OUT_DIR, { recursive: true });

  for (const group of GROUPS) {
    const css = emitGroup(group);
    await writeFile(join(OUT_DIR, `${group.file}.css`), css, "utf-8");
  }

  const baseCount = GROUPS.reduce((n, g) => n + g.rules.length, 0);
  const total = GROUPS.reduce(
    (n, g) => n + g.rules.length * (g.responsive ? BREAKPOINTS.length + 1 : 1),
    0,
  );
  console.log(
    `Generated ${GROUPS.length} utility files (${baseCount} base classes, ${total} rules total) in styles/utilities/`,
  );
}

await main();
