/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Typography } = scope;
  return (
<View style={{ gap: 8 }}>
  <Typography display>Welcome</Typography>
  <Typography display>Get started</Typography>
</View>
  );
}
