/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Typography } = scope;
  return (
<View>
  <Typography h4>Notifications</Typography>
  <Typography small style={{ marginTop: 4 }}>Choose how and when we reach you.</Typography>
</View>
  );
}
