/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Typography, Row } = scope;
  return (
<Row alignCenter snug>
  <Typography body>Deploy succeeded</Typography>
  <Typography tiny>3m ago</Typography>
</Row>
  );
}
