/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Typography, Column } = scope;
  return (
<Column tight>
  <Typography caption>Billing</Typography>
  <Typography body>Your subscription renews automatically each month.</Typography>
</Column>
  );
}
