/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Typography, Column } = scope;
  return (
<Column tight>
  <Typography h5>Members</Typography>
  <Typography body>Aisha, Bao, Cleo, and 9 others have access.</Typography>
</Column>
  );
}
