/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Typography } = scope;
  return (
<Typography body>
  Create a branch with 
  <Typography code>git checkout -b feature</Typography>
   before committing.
</Typography>
  );
}
