/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Typography } = scope;
  return (
<View>
  <Typography caption>Billing</Typography>
  <Typography body style={{ marginTop: 4 }}>Your subscription renews automatically each month.</Typography>
</View>
  );
}
