/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Typography } = scope;
  return (
<View>
  <Typography display>Welcome</Typography>
  <Typography muted style={{ marginTop: 8 }}>Sign in to pick up where you left off.</Typography>
</View>
  );
}
