/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Typography, Column } = scope;
  return (
<Column tight>
  <Typography h4>Notifications</Typography>
  <Typography small>Choose how and when we reach you.</Typography>
</Column>
  );
}
