/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Typography } = scope;
  return (
<Button secondary>
  <Typography small>Save changes</Typography>
</Button>
  );
}
