/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/checkbox/checkbox.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Checkbox, Select, Column } = scope;
  return (
<Column snug>
  <Checkbox indeterminate>Select all</Checkbox>
  <Column snug indent>
    <Checkbox defaultChecked>Read</Checkbox>
    <Checkbox>Write</Checkbox>
    <Checkbox>Delete</Checkbox>
  </Column>
</Column>
  );
}
