/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/checkbox/checkbox.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Checkbox } = scope;
  return (
<View style={{ flexDirection: "row", alignItems: "center", gap: 6 }}>
  <Checkbox disabled>Export to CSV</Checkbox>
  <Text style={{ fontSize: 12, lineHeight: 16, color: tokens["muted-foreground"] }}>(Pro plan)</Text>
</View>
  );
}
