/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/fieldset/fieldset.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Fieldset } = scope;
  return (
<Fieldset checkboxes={[
    { label: "Email" },
    { label: "SMS" },
    { label: "Push" }
  ]} />
  );
}
