/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/fieldset/fieldset.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Fieldset } = scope;
  return (
<Fieldset legend="Shipping details" items={[
    { label: "Full name", placeholder: "Ada Lovelace" },
    { label: "Email", placeholder: "ada@example.com", help: "We'll only use this for order updates." }
  ]} />
  );
}
