/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/fieldset/fieldset.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Fieldset } = scope;
  return (
<Fieldset legend="Card details" twoColumn items={[
    { label: "Expiry", placeholder: "MM / YY" },
    { label: "CVC", placeholder: "123" }
  ]} />
  );
}
