/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/fieldset/fieldset.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Fieldset } = scope;
  return (
<Fieldset
  legend="Shipping details"
  description="Where should we send your order?"
  items={[
    { label: "Full name", placeholder: "Ada Lovelace" },
    { label: "Email", placeholder: "ada@example.com", value: "ada@", help: "We'll only use this for order updates." },
    { label: "Country", placeholder: "United States" }
  ]}
/>
  );
}
