/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/reveal/reveal.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Reveal, RevealGroup, Typography, Row } = scope;
  return (
<Row cozy wrap>
  <RevealGroup>
    <Reveal fromBelow>
      <Card padded style={{ width: 140 }}>
        <Typography small semibold>Rises</Typography>
      </Card>
    </Reveal>
    <Reveal fromBelow>
      <Card padded style={{ width: 140 }}>
        <Typography small semibold>Rises</Typography>
      </Card>
    </Reveal>
  </RevealGroup>
</Row>
  );
}
