/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/reveal/reveal.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Reveal, RevealGroup, Typography, Row } = scope;
  return (
<Row cozy wrap>
  <RevealGroup>
    <Reveal>
      <Card padded style={{ width: 140 }}>
        <Typography small semibold>First</Typography>
      </Card>
    </Reveal>
    <Reveal>
      <Card padded style={{ width: 140 }}>
        <Typography small semibold>Second</Typography>
      </Card>
    </Reveal>
    <Reveal>
      <Card padded style={{ width: 140 }}>
        <Typography small semibold>Third</Typography>
      </Card>
    </Reveal>
  </RevealGroup>
</Row>
  );
}
