/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/reveal/reveal.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Card, Typography } = scope;
  return (
<View style={{ opacity: 0.35, width: 300, maxWidth: "100%" }}>
  <Card padded>
    <Typography small semibold>Stuck half-arrived</Typography>
  </Card>
</View>
  );
}
