/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/reveal/reveal.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Ticker, Card, Reveal, RevealGroup, Typography, Row } = scope;
  return (
<Ticker values={[1, 2]} interval={2800}>
  {(pass) => (
    <Row cozy wrap key={pass}>
      <RevealGroup>
        <Reveal>
          <Card padded style={{ width: 150 }}>
            <Typography small semibold>Measure</Typography>
          </Card>
        </Reveal>
        <Reveal>
          <Card padded style={{ width: 150 }}>
            <Typography small semibold>Reveal</Typography>
          </Card>
        </Reveal>
        <Reveal>
          <Card padded style={{ width: 150 }}>
            <Typography small semibold>Settle</Typography>
          </Card>
        </Reveal>
      </RevealGroup>
    </Row>
  )}
</Ticker>
  );
}
