/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/tooltip/tooltip.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Tooltip } = scope;
  return (
<View style={{ alignItems: "flex-end" }}>
  <Tooltip iconTrigger right open label="More info" />
</View>
  );
}
