/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/tooltip/tooltip.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Tooltip } = scope;
  return (
<View style={{ overflow: "hidden", alignItems: "flex-start" }}>
  <View style={{ marginLeft: -44 }}>
    <Tooltip iconTrigger left open label="Need help?" />
  </View>
</View>
  );
}
