/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/calendar/calendar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Calendar, Typography, Row, Column } = scope;
  return (
<Row loose wrap alignStart>
  <Column tight>
    <Typography small muted>Check-in</Typography>
    <Calendar month="May 2026" defaultSelected={14} daysInMonth={31} startWeekday={4} />
  </Column>
  <Column tight>
    <Typography small muted>Check-out</Typography>
    <Calendar month="May 2026" defaultSelected={20} daysInMonth={31} startWeekday={4} />
  </Column>
</Row>
  );
}
