/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/calendar/calendar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Calendar, Card, CardContent, CardHeader, CardSeparator, Divider, Typography, Row, Column } = scope;
  return (
<Row loose wrap alignStart>
  <Calendar month="May 2026" today={23} defaultSelected={24} daysInMonth={31} startWeekday={4} />
  <Card grow flush style={{ minWidth: 240 }}>
    <CardHeader>
      <Typography small semibold>May 24</Typography>
    </CardHeader>
    <CardSeparator />
    <CardContent>
      <Column tight>
        <Row between alignCenter>
          <Typography small medium>Sprint planning</Typography>
          <Typography small muted>9:00 AM</Typography>
        </Row>
        <Divider />
        <Row between alignCenter>
          <Typography small medium>Design review</Typography>
          <Typography small muted>11:30 AM</Typography>
        </Row>
        <Divider />
        <Row between alignCenter>
          <Typography small medium>1:1 with manager</Typography>
          <Typography small muted>2:00 PM</Typography>
        </Row>
      </Column>
    </CardContent>
  </Card>
</Row>
  );
}
