/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/calendar/calendar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Calendar, Row } = scope;
  return (
<Row loose wrap alignStart>
  <Calendar
    compact
    month="May 2026"
    today={23}
    defaultSelected={24}
    daysInMonth={31}
    startWeekday={4}
    events={[{ day: 8 }, { day: 14 }, { day: 24 }]}
  />
  <Calendar
    compact
    day
    month="May 2026"
    defaultSelected={24}
    daysInMonth={31}
    startWeekday={4}
    events={[
      { day: 24, title: "Sprint planning", start: 9, end: 10.5 },
      { day: 24, title: "Design review", start: 11.5, end: 13 }
    ]}
  />
</Row>
  );
}
