/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/overlays/overlays.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { RowMenu } = scope;
  return (
<RowMenu open sectionLabel="Actions" items={[
    { label: "Edit", icon: "✎" },
    { label: "Duplicate", icon: "⧉" },
    { label: "Delete", icon: "🗑", destructive: true, separatorBefore: true }
  ]} />
  );
}
