/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/textarea/textarea.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Textarea, Typography, Column } = scope;
  return (
<Column snug>
  <Typography small medium>Description</Typography>
  <Textarea rows={3} wide disabled value="Read-only content the user must not change." />
</Column>
  );
}
