/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/textarea/textarea.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Textarea, Typography, Row, Column } = scope;
  return (
<Column snug style={{ maxWidth: 400 }}>
  <Typography small medium>Bio</Typography>
  <Textarea rows={3} invalid value="I have been building things on the web for fifteen years and counting, across teams large and small, shipping product end to end." />
  <Row end>
    <Typography tiny destructive>123 / 120</Typography>
  </Row>
</Column>
  );
}
