/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/textarea/textarea.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Textarea, Typography, Row, Column } = scope;
  return (
<Column tight style={{ maxWidth: 400 }}>
  <Typography small medium>Description</Typography>
  <Textarea rows={4} placeholder="A few words about this project…" />
  <Row end>
    <Typography tiny muted>0 / 280</Typography>
  </Row>
</Column>
  );
}
