/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/textarea/textarea.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Textarea } = scope;
  return (
<Textarea label="Description" rows={4} defaultValue="Canvas renders the same components natively on iOS and Android and on the web." />
  );
}
