/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/textarea/textarea.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, alpha, View, Button, Textarea } = scope;
  return (
<View style={{ maxWidth: 400, overflow: "hidden", borderRadius: 6, borderWidth: 1, borderColor: tokens.border }}>
  <View style={{ flexDirection: "row", alignItems: "center", gap: 4, borderBottomWidth: 1, borderColor: tokens.border, backgroundColor: alpha(tokens.muted, 0.3), paddingHorizontal: 12, paddingVertical: 8 }}>
    <Button ghost small style={{ minWidth: 32, paddingHorizontal: 8 }}>B</Button>
    <Button ghost small style={{ minWidth: 32, paddingHorizontal: 8 }}>I</Button>
    <Button ghost small style={{ minWidth: 32, paddingHorizontal: 8 }}>{"</>"}</Button>
    <View style={{ marginHorizontal: 4, height: 16, width: 1, backgroundColor: tokens.border }} />
    <Button ghost small style={{ paddingHorizontal: 12 }}>Comment</Button>
  </View>
  <Textarea rows={4} placeholder="Leave a comment…" style={{ minHeight: 104, width: "100%", borderRadius: 0, borderWidth: 0 }} />
</View>
  );
}
