/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/overlays/overlays.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Toast } = scope;
  return (
<Toast
  message="Identity deleted"
  description="You can undo this for 10 seconds."
  action={{ label: "Undo", onPress: () => {} }}
  onDismiss={() => {}}
/>
  );
}
