/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/overlays/overlays.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, alpha, shadow, View, Text, Pressable, Button } = scope;
  return (
<View style={{ flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12, borderRadius: 8, borderWidth: 1, borderColor: alpha(tokens.destructive, 0.3), backgroundColor: tokens.popover, paddingHorizontal: 16, paddingVertical: 12, ...shadow("lg") }}>
  <View>
    <Text style={{ fontSize: 14, lineHeight: 20, fontWeight: "500", color: tokens["popover-foreground"] }}>Delete this identity?</Text>
    <View style={{ marginTop: 8, flexDirection: "row", gap: 8 }}>
      <Button outline small>Cancel</Button>
      <Button destructive small>Delete</Button>
    </View>
  </View>
  <Pressable style={({ pressed }) => [pressed ? { opacity: 0.7 } : null]}>
    <Text style={{ color: tokens["muted-foreground"] }}>×</Text>
  </Pressable>
</View>
  );
}
