/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/overlays/overlays.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Dialog } = scope;
  return (
<Dialog open destructive title="Delete identity?" description="This cannot be undone." confirmLabel="Delete" cancelLabel="Cancel" />
  );
}
