/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/overlays/overlays.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Overlay } = scope;
  return (
<Overlay
  trigger="Open panel"
  title="Edit Identity"
  description="Visible above the parent page so the user can compare."
  drawer
/>
  );
}
