/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/button/button.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Button } = scope;
  return (
<View style={{ flexDirection: "row", alignItems: "center", gap: 12 }}>
  <Button primary>Submit</Button>
  <Button link>Learn more</Button>
</View>
  );
}
