import {
  View,
  Text,
  Pressable,
  Image,
  TextInput,
  ScrollView,
  Accordion,
  ActionPanel,
  ActionSheet,
  Alert,
  AlertDialog,
  Autocomplete,
  Avatar,
  Badge,
  Breadcrumb,
  Button,
  ButtonGroup,
  Calendar,
  Carousel,
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardMedia,
  CardSeparator,
  CardTitle,
  Chart,
  Checkbox,
  CodeBlock,
  Collapsible,
  Command,
  DataTable,
  DescriptionList,
  Dialog,
  Draggable,
  DragDropProvider,
  DragHandle,
  DropZone,
  Drawer,
  Divider,
  Dropdown,
  EmptyState,
  Feed,
  Field,
  Fieldset,
  FilterPanel,
  Form,
  FormSection,
  GridList,
  Icon,
  Input,
  InputOTP,
  Kbd,
  Listbox,
  MediaObject,
  Navbar,
  Overlay,
  Pagination,
  Popover,
  Progress,
  QRCode,
  Radio,
  RadioGroup,
  RowMenu,
  Select,
  Sidebar,
  Skeleton,
  Slider,
  Spinner,
  StackedList,
  Stats,
  Stepper,
  Steps,
  Switch,
  TabBar,
  Tabs,
  Textarea,
  Toast,
  Tooltip,
  Typography,
  Row,
  Column,
  AvatarGroup,
  BadgeGroup,
  Chip,
  Emblem,
  Sparkline,
  StackedBar,
  Gauge,
  Heatmap,
  LineChart,
  AreaChart,
  PieChart,
  ScatterPlot,
  CandlestickChart,
  DepthChart,
} from "@nannier/canvas";

// Style helpers an example fence can reference when it styles a raw View/Text.
// These model how a real consumer builds RN styles: `tokens` (the active,
// theme-aware color set, injected live by the Playground), `alpha`/`shadow`
// helpers, and the `palette` of fixed Tailwind hues. Imported from src/style so
// they're available regardless of what the package barrel currently re-exports.
import { alpha, shadow, palette } from "../../../src/style/index.js";
// Docs-only live-example state helper (not a Canvas export); lets a fence drive a
// component's controlled `value` from an external control. See ./live-state.tsx.
import { Stateful, Ticker, applyDrop, IconGallery } from "./live-state.js";

// The canonical list of names a component `.md` example fence may reference as a JSX
// tag, mapped to the real Canvas components. The docgen (tools/docgen) parses these
// keys so the destructure list it generates for each fence can never drift from the
// real exports; keeping the values as real imports means a name here is always a live
// component. Every JSX tag used across the component docs must appear here. The values
// are opaque to the consumers that read them, hence `unknown`.
export const LIVE_SCOPE: Record<string, unknown> = {
  // Theme/style helpers for example fences that style a raw View/Text. `tokens`
  // is a placeholder here; <LiveExample> swaps in the live, theme-aware value
  // (so token colors follow the docs light/dark + glass toggles).
  tokens: {},
  alpha,
  shadow,
  palette,
  Stateful,
  Ticker,
  applyDrop,
  IconGallery,
  View,
  Text,
  Pressable,
  Image,
  TextInput,
  ScrollView,
  Accordion,
  ActionPanel,
  ActionSheet,
  Alert,
  AlertDialog,
  Autocomplete,
  Avatar,
  Badge,
  Breadcrumb,
  Button,
  ButtonGroup,
  Calendar,
  Carousel,
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardMedia,
  CardSeparator,
  CardTitle,
  Chart,
  Checkbox,
  CodeBlock,
  Collapsible,
  Command,
  DataTable,
  DescriptionList,
  Dialog,
  Draggable,
  DragDropProvider,
  DragHandle,
  DropZone,
  Drawer,
  Divider,
  Dropdown,
  EmptyState,
  Feed,
  Field,
  Fieldset,
  FilterPanel,
  Form,
  FormSection,
  GridList,
  Icon,
  Input,
  InputOTP,
  Kbd,
  Listbox,
  MediaObject,
  Navbar,
  Overlay,
  Pagination,
  Popover,
  Progress,
  QRCode,
  Radio,
  RadioGroup,
  RowMenu,
  Select,
  Sidebar,
  Skeleton,
  Slider,
  Spinner,
  StackedList,
  Stats,
  Stepper,
  Steps,
  Switch,
  TabBar,
  Tabs,
  Textarea,
  Toast,
  Tooltip,
  Typography,
  Row,
  Column,
  AvatarGroup,
  BadgeGroup,
  Chip,
  Emblem,
  Sparkline,
  StackedBar,
  Gauge,
  Heatmap,
  LineChart,
  AreaChart,
  PieChart,
  ScatterPlot,
  CandlestickChart,
  DepthChart,
};
