/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/heatmap/heatmap.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Heatmap } = scope;
  return (
<Card padded style={{ maxWidth: 320 }}>
  <Heatmap label="Contribution activity" values={[0.06, 0.83, 0.38, 0.86, 0.0, 0.73, 0.13, 0.0, 0.0, 0.97, 0.95, 0.28, 0.2, 0.3, 0.37, 0.6, 0.61, 0.17, 0.22, 0.73, 0.13, 0.23, 0.01, 0.56, 0.7, 0.13, 0.03, 0.96, 0.01, 0.21, 0.21, 0.01, 0.01, 0.39, 0.6, 0.01, 0.37, 0.86, 0.07, 0.35, 0.12, 0.1, 0.26, 0.51, 0.1, 0.03, 0.76, 0.39, 0.14, 0.99, 0.23, 0.03, 0.06, 0.85, 0.35, 0.24, 0.03, 0.19, 0.03, 0.0, 0.48, 0.58, 0.02, 0.29, 0.55, 0.78, 0.14, 0.17, 0.41, 0.69]} />
</Card>
  );
}
