/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/filter-panel/filter-panel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Icon, Row } = scope;
  return (
<Row wrap alignCenter snug>
  <Button primary small iconRight={<Icon chevronDown primaryForeground size={12} />}>Status</Button>
  <Button outline small iconRight={<Icon chevronDown size={12} />}>Role</Button>
  <Button link small iconLeft={<Icon plus size={14} />}>Add filter</Button>
</Row>
  );
}
