/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/filter-panel/filter-panel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Row, Chip } = scope;
  return (
<Row wrap snug>
  <Chip primary onRemove={() => {}}>Active</Chip>
  <Chip primary onRemove={() => {}}>Default</Chip>
</Row>
  );
}
