/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/filter-panel/filter-panel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { FilterPanel } = scope;
  return (
<FilterPanel
  bordered
  groups={[
    { title: "Status", options: [
      { label: "Active", checked: true, count: "128" },
      { label: "Pending", count: "12", checked: false },
      { label: "Archived", count: "2", checked: false }
    ] },
    { title: "Schema", options: [
      { label: "Default", checked: true, count: "96" },
      { label: "Custom", count: "46", checked: false }
    ] },
    { title: "MFA", options: [
      { label: "Enabled", count: "84", checked: false },
      { label: "Disabled", count: "58", checked: false }
    ] }
  ]}
/>
  );
}
