/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Typography, Row, Column } = scope;
  return (
<Row between alignEnd wrap snug>
  <Column tight shrink>
    <Typography h5>Sessions</Typography>
    <Typography small muted>Every session Kratos is holding open, newest first.</Typography>
  </Column>
  <Button primary small>Revoke all</Button>
</Row>
  );
}
