/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Typography, Row } = scope;
  return (
<Row between alignCenter>
  <Typography small>Total</Typography>
  <Typography h5>$1,240.00</Typography>
</Row>
  );
}
