/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Text, Button } = scope;
  return (
<View style={{ flexDirection: "row", justifyContent: "space-between", gap: 8 }}>
  <View style={{ flexShrink: 1, minWidth: 0 }}>
    <Text style={{ fontSize: 16, fontWeight: "600" }}>Sessions</Text>
    <Text style={{ fontSize: 13, color: "#71717a" }}>Every session Kratos is holding open, newest first.</Text>
  </View>
  <Button primary small>Revoke all</Button>
</View>
  );
}
