/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Text } = scope;
  return (
<View style={{ flexDirection: "row" }}>
  <Text style={{ fontSize: 14, color: "#71717a" }}>Total</Text>
  <Text style={{ marginLeft: "auto", fontWeight: "600" }}>$1,240.00</Text>
</View>
  );
}
