/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Avatar, Typography, Row, Column } = scope;
  return (
<Row alignCenter relaxed pad>
  <Avatar name="RC" />
  <Column tight>
    <Typography h5>Rachel Chen</Typography>
    <Typography small>rachel.chen@example.com</Typography>
  </Column>
</Row>
  );
}
