/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Input, Row } = scope;
  return (
<Row stacks between alignCenter relaxed>
  <Input placeholder="Search runs…" />
  <Row snug>
    <Button outline>Filter</Button>
    <Button primary>New run</Button>
  </Row>
</Row>
  );
}
