/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { MediaObject, Row } = scope;
  return (
<Row relaxed pad>
  <MediaObject avatar="RC" title="Rachel Chen" description="rachel.chen@example.com" />
</Row>
  );
}
