/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { alpha, Badge, Row } = scope;
  return (
<Row wrap snug>
  <Badge>alpha</Badge>
  <Badge>beta</Badge>
  <Badge>gamma</Badge>
  <Badge>delta</Badge>
  <Badge>epsilon</Badge>
  <Badge>zeta</Badge>
</Row>
  );
}
