/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Badge, Row } = scope;
  return (
<Row center alignCenter snug>
  <Badge>schema</Badge>
  <Badge secondary>role</Badge>
  <Badge outline>tag</Badge>
</Row>
  );
}
