/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/image/image.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Image } = scope;
  return (
<Image
  source={{ uri: "https://picsum.photos/seed/canvas/240/160" }}
  style={{ width: 240, height: 160, borderRadius: 12 }}
/>
  );
}
