/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/image/image.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Image } = scope;
  return (
<Image
  source={{ uri: "https://picsum.photos/seed/ada/80/80" }}
  style={{ width: 80, height: 80, borderRadius: 40 }}
/>
  );
}
