/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/text/text.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Typography, Column } = scope;
  return (
<Column tight>
  <Typography h3>Heading</Typography>
  <Typography body>Body text</Typography>
  <Typography tiny muted>Muted caption</Typography>
</Column>
  );
}
