/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/text/text.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, alpha, View, Text } = scope;
  return (
<View style={{ gap: 6 }}>
  <Text style={{ fontSize: 22, fontWeight: "700", color: tokens.foreground }}>Heading</Text>
  <Text style={{ fontSize: 14, color: tokens.foreground }}>Body text</Text>
  <Text style={{ fontSize: 12, color: alpha(tokens.foreground, 0.6) }}>Muted caption</Text>
</View>
  );
}
