/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/text/text.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, Text } = scope;
  return (
<Text style={{ fontSize: 16, fontWeight: "600", color: tokens.foreground }}>
  The quick brown fox jumps over the lazy dog.
</Text>
  );
}
