/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/divider/divider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Button, Divider } = scope;
  return (
<View style={{ width: 320 }}>
  <View style={{ gap: 8 }}>
    <View style={{ borderRadius: 6, borderWidth: 1, borderColor: tokens.border, paddingHorizontal: 12, paddingVertical: 8 }}>
      <Text style={{ fontSize: 14, lineHeight: 20, color: tokens.foreground }}>Ada commented on the draft</Text>
    </View>
    <View style={{ borderRadius: 6, borderWidth: 1, borderColor: tokens.border, paddingHorizontal: 12, paddingVertical: 8 }}>
      <Text style={{ fontSize: 14, lineHeight: 20, color: tokens.foreground }}>Grace approved the request</Text>
    </View>
  </View>
  <Divider style={{ marginTop: 12 }} children={<Button ghost small>Show more</Button>} />
</View>
  );
}
