/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/qrcode/qrcode.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { QRCode } = scope;
  return (
<QRCode value="https://canvas.olympusoss.com/get/the/app?ref=docs&utm=homepage&v=2" small />
  );
}
