/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/kbd/kbd.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Kbd } = scope;
  return (
<View style={{ flexDirection: "row", alignItems: "center", gap: 4 }}>
  <Kbd>⌘</Kbd>
  <Text style={{ fontSize: 12, lineHeight: 16, color: tokens["muted-foreground"] }}>+</Text>
  <Kbd>⇧</Kbd>
  <Text style={{ fontSize: 12, lineHeight: 16, color: tokens["muted-foreground"] }}>+</Text>
  <Kbd>P</Kbd>
</View>
  );
}
