/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/toast/toast.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { WithToast, AppScreen, Button, ToastProvider, useToast } = scope;
  return (
<AppScreen>
  <ToastProvider>
    <WithToast hook={useToast}>
      {({ toast }) => (
        <Button
          primary
          onPress={() =>
            toast({
              success: true,
              message: "Profile updated",
              description: "Your changes are now live.",
              action: { label: "Undo", onPress: () => {} },
            })
          }
        >
          Show toast
        </Button>
      )}
    </WithToast>
  </ToastProvider>
</AppScreen>
  );
}
