/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/toast/toast.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Toast } = scope;
  return (
<Toast error message="Upload failed" description="Check your connection and try again." action={{ label: "Retry", onPress: () => {} }} />
  );
}
