/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/toast/toast.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Toast } = scope;
  return (
<Toast success message="Profile updated" description="Your changes are now live." action={{ label: "View", onPress: () => {} }} />
  );
}
