/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/progress/progress.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Progress, Typography, Column } = scope;
  return (
<Column snug style={{ maxWidth: 320 }}>
  <Typography small muted>Connecting…</Typography>
  <Progress indeterminate />
</Column>
  );
}
