/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/progress/progress.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Progress, Typography, Column } = scope;
  return (
<Column snug>
  <Typography small>Importing contacts</Typography>
  <Progress value={0.35} />
</Column>
  );
}
