/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/progress/progress.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Progress, Typography, Row, Column } = scope;
  return (
<Column snug>
  <Row flush between>
    <Typography small>Uploading…</Typography>
    <Typography small muted>72%</Typography>
  </Row>
  <Progress value={0.72} />
</Column>
  );
}
