/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/feeds/feeds.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Feed } = scope;
  return (
<Feed
  connector
  items={[
    { actor: "Rachel Chen", action: "approved the request", time: "2 hours ago" },
    { actor: "Ada Lovelace", action: "updated the description", time: "5 hours ago" },
    { actor: "System", action: "created the project", time: "3 days ago" }
  ]}
/>
  );
}
