/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/emblem/emblem.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Row, Emblem } = scope;
  return (
<Row snug alignCenter>
  <Emblem primary label="U" />
  <Emblem success label="S" />
</Row>
  );
}
