/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/button-group/button-group.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { ButtonGroup } = scope;
  return (
<ButtonGroup
  stepper
  items={[
    "May 21",
    "May 22",
    "May 23",
    "Today",
    "May 25",
    "May 26",
    "May 27"
  ]}
  active={3}
  small
/>
  );
}
