// GENERATED by scripts/capture-looks.ts (full device-screen captures of each atom's
// docs page on the iPhone 17 Pro simulator, the Android emulator retargeted to the same
// screen, and phone-width web; encoded 480x1044 webp). Every surface shares the
// iPhone 17 Pro aspect so the three hero panes are identical. Do not edit by hand.
/* eslint-disable @typescript-eslint/no-require-imports */
export const LOOKS_SHOTS: Record<string, { ios: number; android: number; web: number }> = {
  "autocomplete": { ios: require("../../assets/images/looks/autocomplete-ios.webp"), android: require("../../assets/images/looks/autocomplete-android.webp"), web: require("../../assets/images/looks/autocomplete-web.webp") },
  "avatar": { ios: require("../../assets/images/looks/avatar-ios.webp"), android: require("../../assets/images/looks/avatar-android.webp"), web: require("../../assets/images/looks/avatar-web.webp") },
  "badge": { ios: require("../../assets/images/looks/badge-ios.webp"), android: require("../../assets/images/looks/badge-android.webp"), web: require("../../assets/images/looks/badge-web.webp") },
  "breadcrumb": { ios: require("../../assets/images/looks/breadcrumb-ios.webp"), android: require("../../assets/images/looks/breadcrumb-android.webp"), web: require("../../assets/images/looks/breadcrumb-web.webp") },
  "button": { ios: require("../../assets/images/looks/button-ios.webp"), android: require("../../assets/images/looks/button-android.webp"), web: require("../../assets/images/looks/button-web.webp") },
  "button-group": { ios: require("../../assets/images/looks/button-group-ios.webp"), android: require("../../assets/images/looks/button-group-android.webp"), web: require("../../assets/images/looks/button-group-web.webp") },
  "checkbox": { ios: require("../../assets/images/looks/checkbox-ios.webp"), android: require("../../assets/images/looks/checkbox-android.webp"), web: require("../../assets/images/looks/checkbox-web.webp") },
  "chip": { ios: require("../../assets/images/looks/chip-ios.webp"), android: require("../../assets/images/looks/chip-android.webp"), web: require("../../assets/images/looks/chip-web.webp") },
  "divider": { ios: require("../../assets/images/looks/divider-ios.webp"), android: require("../../assets/images/looks/divider-android.webp"), web: require("../../assets/images/looks/divider-web.webp") },
  "dropdown": { ios: require("../../assets/images/looks/dropdown-ios.webp"), android: require("../../assets/images/looks/dropdown-android.webp"), web: require("../../assets/images/looks/dropdown-web.webp") },
  "emblem": { ios: require("../../assets/images/looks/emblem-ios.webp"), android: require("../../assets/images/looks/emblem-android.webp"), web: require("../../assets/images/looks/emblem-web.webp") },
  "icon": { ios: require("../../assets/images/looks/icon-ios.webp"), android: require("../../assets/images/looks/icon-android.webp"), web: require("../../assets/images/looks/icon-web.webp") },
  "image": { ios: require("../../assets/images/looks/image-ios.webp"), android: require("../../assets/images/looks/image-android.webp"), web: require("../../assets/images/looks/image-web.webp") },
  "input": { ios: require("../../assets/images/looks/input-ios.webp"), android: require("../../assets/images/looks/input-android.webp"), web: require("../../assets/images/looks/input-web.webp") },
  "input-otp": { ios: require("../../assets/images/looks/input-otp-ios.webp"), android: require("../../assets/images/looks/input-otp-android.webp"), web: require("../../assets/images/looks/input-otp-web.webp") },
  "kbd": { ios: require("../../assets/images/looks/kbd-ios.webp"), android: require("../../assets/images/looks/kbd-android.webp"), web: require("../../assets/images/looks/kbd-web.webp") },
  "listbox": { ios: require("../../assets/images/looks/listbox-ios.webp"), android: require("../../assets/images/looks/listbox-android.webp"), web: require("../../assets/images/looks/listbox-web.webp") },
  "pagination": { ios: require("../../assets/images/looks/pagination-ios.webp"), android: require("../../assets/images/looks/pagination-android.webp"), web: require("../../assets/images/looks/pagination-web.webp") },
  "popover": { ios: require("../../assets/images/looks/popover-ios.webp"), android: require("../../assets/images/looks/popover-android.webp"), web: require("../../assets/images/looks/popover-web.webp") },
  "pressable": { ios: require("../../assets/images/looks/pressable-ios.webp"), android: require("../../assets/images/looks/pressable-android.webp"), web: require("../../assets/images/looks/pressable-web.webp") },
  "progress": { ios: require("../../assets/images/looks/progress-ios.webp"), android: require("../../assets/images/looks/progress-android.webp"), web: require("../../assets/images/looks/progress-web.webp") },
  "qrcode": { ios: require("../../assets/images/looks/qrcode-ios.webp"), android: require("../../assets/images/looks/qrcode-android.webp"), web: require("../../assets/images/looks/qrcode-web.webp") },
  "radio": { ios: require("../../assets/images/looks/radio-ios.webp"), android: require("../../assets/images/looks/radio-android.webp"), web: require("../../assets/images/looks/radio-web.webp") },
  "row-column": { ios: require("../../assets/images/looks/row-column-ios.webp"), android: require("../../assets/images/looks/row-column-android.webp"), web: require("../../assets/images/looks/row-column-web.webp") },
  "scroll-view": { ios: require("../../assets/images/looks/scroll-view-ios.webp"), android: require("../../assets/images/looks/scroll-view-android.webp"), web: require("../../assets/images/looks/scroll-view-web.webp") },
  "select": { ios: require("../../assets/images/looks/select-ios.webp"), android: require("../../assets/images/looks/select-android.webp"), web: require("../../assets/images/looks/select-web.webp") },
  "skeleton": { ios: require("../../assets/images/looks/skeleton-ios.webp"), android: require("../../assets/images/looks/skeleton-android.webp"), web: require("../../assets/images/looks/skeleton-web.webp") },
  "slider": { ios: require("../../assets/images/looks/slider-ios.webp"), android: require("../../assets/images/looks/slider-android.webp"), web: require("../../assets/images/looks/slider-web.webp") },
  "sparkline": { ios: require("../../assets/images/looks/sparkline-ios.webp"), android: require("../../assets/images/looks/sparkline-android.webp"), web: require("../../assets/images/looks/sparkline-web.webp") },
  "spinner": { ios: require("../../assets/images/looks/spinner-ios.webp"), android: require("../../assets/images/looks/spinner-android.webp"), web: require("../../assets/images/looks/spinner-web.webp") },
  "stepper": { ios: require("../../assets/images/looks/stepper-ios.webp"), android: require("../../assets/images/looks/stepper-android.webp"), web: require("../../assets/images/looks/stepper-web.webp") },
  "switch": { ios: require("../../assets/images/looks/switch-ios.webp"), android: require("../../assets/images/looks/switch-android.webp"), web: require("../../assets/images/looks/switch-web.webp") },
  "text": { ios: require("../../assets/images/looks/text-ios.webp"), android: require("../../assets/images/looks/text-android.webp"), web: require("../../assets/images/looks/text-web.webp") },
  "text-input": { ios: require("../../assets/images/looks/text-input-ios.webp"), android: require("../../assets/images/looks/text-input-android.webp"), web: require("../../assets/images/looks/text-input-web.webp") },
  "textarea": { ios: require("../../assets/images/looks/textarea-ios.webp"), android: require("../../assets/images/looks/textarea-android.webp"), web: require("../../assets/images/looks/textarea-web.webp") },
  "tooltip": { ios: require("../../assets/images/looks/tooltip-ios.webp"), android: require("../../assets/images/looks/tooltip-android.webp"), web: require("../../assets/images/looks/tooltip-web.webp") },
  "typography": { ios: require("../../assets/images/looks/typography-ios.webp"), android: require("../../assets/images/looks/typography-android.webp"), web: require("../../assets/images/looks/typography-web.webp") },
  "view": { ios: require("../../assets/images/looks/view-ios.webp"), android: require("../../assets/images/looks/view-android.webp"), web: require("../../assets/images/looks/view-web.webp") },
};

export const LOOKS_ASPECT = 1206 / 2622;
