/* @generated by tools/docgen — DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/dropdown/dropdown.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Dropdown } = scope;
  return (
<Dropdown trigger="Actions" label="Create" items={[
    { label: "New file" },
    { label: "New folder" },
    { label: "Upload" },
    { label: "Rename", separatorBefore: true },
    { label: "Move to…" },
    { label: "Download" }
  ]} />
  );
}
